#!/usr/bin/ruby

files = %w{vendor/jquery.tipsy init plugins/t10n locale/en plugins/isValid markupEditor util plugins/enhanceTextfield plugins/combobox dialog modes/textile/textileMode modes/textile/bruteForceCompiler modes/wysiwygMode modes/hamlMode}

File.open('source/javascripts/joined.js','w') do |file|
  files.each do |filename|
    regexp = /( # Match she-bang style C-comment
    \/\*[!*]   # Opening delimiter.
    [^*]*\*+    # {normal*} Zero or more non-*, one or more *
    (?:         # Begin {(special normal*)*} construct.
      [^*\/]    # {special} a non-*, non-\/ following star.
      [^*]*\*+  # More {normal*}
    )*          # Finish "Unrolling-the-Loop"
    \/          # Closing delimiter.
    |           # Or
    $\s*\/\/.*      # One line comments
    )/x

    file.puts File.open('source/javascripts/' + filename + '.js').read #.gsub(regexp, '')
  end
end

require 'rubygems'
require 'closure-compiler'
File.open('source/javascripts/joined-min.js','w') do |file|
  # closure = Closure::Compiler.new(:compilation_level => 'ADVANCED_OPTIMIZATIONS')
  closure = Closure::Compiler.new
  file.puts closure.compile(File.open('source/javascripts/joined.js', 'r'))
end

