(function(f){var d,j={check:function(){var e=true;this.find(d.errorElement+"."+d.errorClass).remove();this.find(":input."+d.inputErrorClass).removeClass(d.inputErrorClass);this.find(":input.required").each(function(){var r=f(this),j=f.trim(r.val()),s=r.siblings("label").text().replace(d.removeLabelChar,""),p="";if(j==="")p=hasLabelPlaceholder?p=d.errorText.replace("{label}",s):p=d.errorText,e=false;else if(r.hasClass("email")&&!/^([_a-z0-9-]+)(\.[_a-z0-9-]+)*@([a-z0-9-]+)(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/.test(j))p=
hasLabelPlaceholder?p=d.emailErrorText.replace("{label}",s):p=d.emailErrorText,e=false;p!==""&&r.parent().addClass(d.errorClass)});return e},reset:function(){return this.find(":input.required").each(function(){f(this).parent().removeClass(d.errorClass)})}};f.fn.isValid=function(e){j[e]||(e="check");return j[e].apply(this,Array.prototype.slice.call(arguments,1))};f.fn.isValid.init=function(e){d=f.extend({},f.fn.isValid.defaults,e);hasLabelPlaceholder=d.errorText.indexOf("{label}")>-1};f.fn.isValid.defaults=
{errorClass:"error",errorText:"{label} is a required field.",emailErrorText:"Please enter a valid {label}",errorElement:"strong",removeLabelChar:"*"}})(jQuery);
(function(f){function d(b){f.extend(this,b);this.prototype=d.prototype}function j(b,n,g){this.name=b;this.isAvailable=g;if(n)this.clicked=n,t.push(b)}function e(b,n,g){j.apply(this,[b,g]);this.options=n||[]}function r(){var b,n,g;if(!c)for(b=0,n=q.length;b<n;b++)(g=a[q[b]])&&(c+=g.getButton());return c}function u(b){var n=f('<div class="toolbar"></div>'),g=this;this.div=n;n.html(r());n.mouseup(function(n){n=n.target;if(/(a|span)/i.test(n.nodeName)){if(/span/i.test(n.nodeName))n=n.parentNode;if(n.disabled)return b.is("wysiwyg")?
b.htmlDiv.focus():b.textArea.focus(),false;var a=n.className,a=a.split(" ")[0];g.runAction(b,a,n);b.checkState()}}).change(function(n){n=n.target;g.runAction(b,n.className,n);return false}).click(function(){return false})}function s(b,n){function g(b,g){b.keydown(function(b){if(g||a.is("wysiwyg"))return a.currentMode.pressed(a,b.keyCode)}).keyup(function(b){if(g||a.is("wysiwyg"))return a.currentMode.released(a,b.keyCode)}).mouseup(function(){if(g||a.is("wysiwyg"))return a.focus(),a.currentMode.clicked(a)})}
var a=this,m=0,c=n.htmlDiv;this.setDataType(b.attr("class"));this.settings=n;if(this.dataType)this.textArea=b.bind("mouseup keyup",function(){a.checkState();clearTimeout(m);m=setTimeout(function(){a.currentMode.updatePreview(a)},1E3)}),g(b,true),c?c.addClass("preview"):c=f('<div class="preview"></div>'),this.htmlDiv=c.bind("mouseup keyup",function(){a.is("wysiwyg")&&a.checkState()}),g(this.htmlDiv),this.toolbar=new u(this),this.container=b.wrap('<div class="markupEditor"></div>').parent().append(a.htmlDiv).prepend(this.toolbar.div),
b.wrap('<div class="textarea">'),v[l]=a,a.id=l,l++}function p(b,a){var g;g={};f.extend(g,h,a);g=new s(b,g);g.currentMode=g.getDataMode();if(b.hasClass("wysiwyg"))g.currentMode.activate(g),g.currentMode=ME.getMode("wysiwyg");g.currentMode.activate(g);g.checkState();return g}var h={},k={},a={},c="",q="bold,italic,alignLeft,alignCenter,alignRight,unorderedList,orderedList,link,insertImage,save,wysiwyg,close,changeDataMode,formatBlock".split(","),t=[],v=[],l=0,o;d.prototype={pressed:function(b){if(b===
16)ME.holdShift=true;if(ME.util.isNeutralKey(b))ME.holdNeutralKey=true},released:function(b){if(b===16)ME.holdShift=false;if(ME.util.isNeutralKey(b))ME.holdNeutralKey=false},clicked:f.noop,activate:function(b){b.htmlDiv.is(":empty")?this.updatePreview(b):this.updateTextArea(b);b.toolbar.loadModeToolbar(b);this.afterActivation(b)},updatePreview:function(b){console.log("updating preview in Mode "+this.name);b.htmlDiv.html(this.toHTML(b)||"<p>&nbsp;</p>")},updateTextArea:function(b){console.log("updating TA in Mode "+
this.name);b.textArea.val(this.toText(b))},afterActivation:function(b){b.textArea.parent().show().find(":first-child").focus()[0].setSelectionRange(0,0);b.htmlDiv.attr("contentEditable",false)},getStates:function(b){b=this.getSelectionStates(b);this.id==="wysiwyg"?b.wysiwyg=true:b.changeDataMode=this.id;return b},getSelectionStates:function(){return{}},buildStateObject:function(b,a){for(var g,c=b.length,m={};c--;)switch(g=b[c],g.tag?g.tag:g.nodeName.toLowerCase()){case "a":a.a=g;m.link=true;break;
case "img":a.img=g;m.insertImage=true;break;case "i":m.italic=true;break;case "b":m.bold=true;break;case "ol":m.orderedList=true;m.unorderedList=false;m.formatBlock="disable";m.alignLeft="disable";m.alignRight="disable";m.alignCenter="disable";a.list=g;break;case "ul":m.orderedList=false;m.unorderedList=true;m.formatBlock="disable";m.alignLeft="disable";m.alignRight="disable";m.alignCenter="disable";a.list=g;break;case "li":break;default:m.formatBlock=g.tag?g.tag:g.nodeName.toLowerCase(),a.block=
g}return m},getSelection:function(b,a){var g=b.textArea,c=g.val(),m;g.focus();b.initSelectionProperties();c[b.selectionEnd-1]==="\n"&&(b.selectionEnd-=1);if(a){m=Math.max(c.lastIndexOf(a,b.selectionStart),c.lastIndexOf("\n",b.selectionStart));b.boundaryStart=m!==-1?m+1:0;m=c.indexOf("\n",b.selectionEnd);g=m===-1?c.slice(b.boundaryStart):c.slice(b.boundaryStart,m);m=0;do m=g.indexOf(a,m+1);while(m!==-1&&b.selectionEnd>b.boundaryStart+m);if(m===-1)m=g.length;b.boundaryEnd=b.boundaryStart+m}b.boundaryDistance=
m;return c.slice(b.boundaryStart,b.boundaryEnd)},extendSelection:function(b,a){var g=this.getSelection(b,a);b.setSelectionRange(b.boundaryStart,b.boundaryEnd);return g},replaceSelection:function(b,a,g){var c=b.textArea,m=b.selectionStart,q=b.selectionStart+a.length;c.val(c.val().slice(0,b.selectionStart)+a+c.val().slice(b.selectionEnd,c.val().length));g===true?q=m:g===false&&(m=q);b.setSelectionRange(m,q);c.focus()},extendRightSelection:function(b,a){var g,a=RegExp(a.source,"g");a.lastIndex=b.selectionEnd;
if((g=a.exec(b.textArea.val()))&&a.lastIndex==b.selectionEnd+g[0].length)return b.selectionEnd+=g[0].length,g[0]},extendLeftSelection:function(b,a){var g;g=b.textArea.val().slice(0,b.selectionStart);a=RegExp(a.source+"$");if(g=a.exec(g))return b.selectionStart-=g[0].length,g[0]}};j.prototype={getButton:function(){return'<a href="#" class="'+this.name+'" ><span>'+this.name+"</span></a>"}};e.prototype={getButton:function(){var b='<select class="'+this.name+'">',a=this.options.length,g;b.className=this.name;
for(g=0;g<a;g+=1)b+='<option value="'+this.options[g][0]+'">'+this.options[g][1]+"</option>";return b+"</select>"}};u.prototype={loadModeToolbar:function(b){var n=b.currentMode.supportedItems,g=this.visibleItems,c=[];this.div.children().each(function(){var m=this.className.split(" ")[0],q=a[m].isAvailable;n.indexOf(m)!=-1&&(!q||q(b))?((!g||g.indexOf(m)==-1)&&f(this).show(),c.push(m)):(!g||g.indexOf(m)!=-1)&&f(this).hide()});this.visibleItems=c},runAction:function(b,n,g){var c=a[n],m=b.currentMode;
(c[m.id]||c).clicked(b,g);n!="changeMode"&&!b.is("wysiwyg")&&m.updatePreview(b)},setActive:function(b){b&&this.div.children().each(function(){var a=this.className.split(" ")[0];if(b[a]=="disable")this.disabled=true,this.className=a+" disabled";else if(this.disabled=false,this.className=a,b[a]===true)this.className=a+" on";else if(b[a])this.value=b[a]})}};s.prototype={changeMode:function(b){b=ME.getMode(b);this.synchronize();this.currentMode=b;b.activate(this)},changeDataMode:function(b){var a=this.is("wysiwyg");
if(!b||b===this.currentMode.id)return false;this.changeMode(b);a&&this.changeMode("wysywyg")},getDataMode:function(){return ME.getMode(this.dataType)},setDataType:function(b){for(var a,g=b.split(/\s+/),b=0;b<g.length;b+=1)if(a=g[b],a!=="wysiwyg"&&k[a])this.dataType=a},initSelectionProperties:function(){var b=this.textArea;this.scrollPosition=b.scrollTop;this.selectionStart=b[0].selectionStart;this.selectionEnd=b[0].selectionEnd},setSelectionRange:function(b,a){this.textArea[0].setSelectionRange(b,
a);this.selectionStart=b;this.selectionEnd=a},synchronize:function(){this.is("wysiwyg")?ME.getMode(this.dataType).updateTextArea(this):this.currentMode.updatePreview(this)},is:function(b){return this.currentMode.id===b},checkState:function(){this.toolbar.setActive(this.currentMode.getStates(this))},focus:function(){o&&v[o].blur();o=this.id},blur:function(){},close:function(){var b=this.settings.htmlDiv||this.textArea;this.synchronize();this.container.replaceWith(b);b.removeClass("preview").unbind().attr("contentEditable",
false).show().markupEditor("prepare",this.settings)}};ME={addMode:function(b,c){var g=c.items,q,m=t.slice();c.id=b;if(g)for(item in g)g.hasOwnProperty(item)&&item!=="default"&&(m.push(item),a[item]||(q=g[item].options?e:j,a[item]=new q(item)),a[item][b]=f.extend({name:item},g["default"],g[item]));b!=="wysiwyg"&&a.changeDataMode.options.push([b,c.name]);c.supportedItems=m;return k[b]=new d(c)},getMode:function(b){var a=k[b];if(a)return a;else console.log("Mode "+b+" is not defined")},options:{},setOptions:function(b){this.options=
b}};a.changeDataMode=new e("changeDataMode",[],function(b,a,g){b.changeDataMode(g.value)});a.formatBlock=new e("formatBlock",[["p","Paragraph"],["h1","Heading 1"],["h2","Heading 2"],["h3","Heading 3"]]);a.save=new j("save",function(b){b.synchronize();b.settings.save(b)},function(b){return b.settings.save});a.wysiwyg=new j("wysiwyg",function(b){b.is("wysiwyg")?b.changeMode(b.dataType):b.changeMode("wysiwyg")});a.close=new j("close",function(b){b.close()},function(b){b=b.settings;return b.htmlDiv||
b.closable});var w={init:function(b){ME.settings=b;return this.each(function(a,g){var c=f(g);if(c.is("textarea"))p(c,b);else{var m=b;c.css("min-height",c.height());var q=f('<textarea class="'+c[0].className+'">');c.before(q);m=m||{};m.htmlDiv=c;c=p(q,m);c.currentMode.updateTextArea(c);c.changeMode("wysiwyg");c.checkState()}})},close:function(){},prepare:function(b){return this.one("click",function(){f(this).markupEditor(b)})}};f.fn.markupEditor=function(b){var a=Array.prototype.slice.call(arguments,
1);typeof b==="object"&&a.push(b);w[b]||(b="init");return w[b].apply(this,a)}})(jQuery);(function(f){neutralKeys="9.16.17.18.20.27.33.34.35.36.37.38.39.40.45.91.93.93";f.util={isNeutralKey:function(d){return neutralKeys.indexOf(""+d)!=-1},isRemovalKey:function(d){return d==46||d==8}}})(ME);
(function(f,d){var j=d.util.isNeutralKey,e=d.util.isRemovalKey;f.fn.enhanceTextfield=function(d){d=d||{};return this.each(function(){function u(){h.css("color","grey").data("hasPrompt",true).val(d.prompt)}function s(){h.css("color",c).data("hasPrompt",false).val("")}function p(){h.val()&&h.val()!==d.prompt?(h.css("color",c),k.show()):(u(),k.hide(),a=false)}var h=f(this),k,a,c=h.css("color");h.is("input")&&(k=f("<span>x</span>").click(function(){s();h.focus();k.hide();a=false}),$p=h.wrap('<span class="clearButton">').focus(function(){!a&&
h.val()===d.prompt&&s();h.parent().addClass("focus")}).focusout(function(){!a&&!h.val()&&u();h.parent().removeClass("focus")}).keydown(function(c){!j(c.which)&&(!a||e(c.which))&&h.val()===d.prompt&&s()}).keyup(function(c){!a&&!j(c.which)&&!e(c.which)&&(a=true,p())}).bind("blur change",function(){p()}).submit(function(){h.val()===d.prompt&&s()}).parent().append(k),h.hasClass("ui-corner-left")?$p.addClass("ui-corner-left"):$p.addClass("ui-corner-all"))})}})(jQuery,ME);
(function(f,d){f.fn.required=function(d){return this.each(function(){d?f(this).addClass("required"):f(this).removeClass("required")})};f.widget("ui.combobox",{_create:function(){var j=this.element,e=this.options.key,r=f.ui.autocomplete.escapeRegex;j.autocomplete({delay:0,minLength:0,source:function(f,j){var p=RegExp(r(f.term),"i"),h=d.options[e]||[],k=h.length,a=[],c,q;if(f.term)for(q=0;q<k;q++)c=h[q],p.test(c)&&a.push({label:c.replace(RegExp("(?![^&;]+;)(?!<[^<>]*)("+r(f.term)+")(?![^<>]*>)(?![^&;]+;)",
"gi"),"<strong>$1</strong>"),value:c});else a=h;j(a)},focus:function(d,e){j.val(e.item.value).change()}}).addClass("ui-corner-left");j.data("autocomplete")._renderItem=function(d,e){return f("<li></li>").data("item.autocomplete",e).append("<a>"+e.label+"</a>").appendTo(d)};this.button=f("<button type='button'>&nbsp;</button>").attr("tabIndex",-1).attr("title","Show All Items").insertAfter(j).button({icons:{primary:"ui-icon-triangle-1-s"},text:false}).removeClass("ui-corner-all").addClass("ui-corner-right ui-button-icon").click(function(){j.autocomplete("widget").is(":visible")?
j.autocomplete("close"):(j.data("hasPrompt")&&j.val(""),j.autocomplete("search",""),j.focus())})},destroy:function(){this.button.remove();f.Widget.prototype.destroy.call(this)}})})(jQuery,ME);
(function(f){function d(d,f,j){var h=f.length,k=d.find(":first-child");d.dialog({autoOpen:false,width:600,close:function(){e.close&&e.close();for(i=0;i<h;i++)f[i].val("").removeAttr("checked").removeAttr("selected")},open:function(){for(i=0;i<h;i++)f[i].change();f[0][0].setSelectionRange(0,0);k.isValid("reset")}});return{dialog:function(a,c){c&&(e=c);d.dialog(a)},find:function(a){return d.find(a)},selectButtons:function(a){for(var c={},q=a.length;q--;)c[a[q]]=j[a[q]];d.dialog("option","buttons",c)},
val:function(a,c){this.find(a).val(c)}}}function j(j,s){var p,h,k,a,c,q,t,v=s.length,l=[];p=f('<div id="'+j+'-dialog" title="'+r[j+"Title"]+'"><form>');var o=p.find(":first-child");for(k=0;k<v;k++){a=s[k][0];c=s[k][1];o.append('<label for="'+a+'">'+r[a]+"</label>");l[k]=f('<input type="text" class="'+a+'" name="'+a+'">').appendTo(o);if(c)for(q in c)c.hasOwnProperty(q)&&(t=c[q],l[k][q](t));l[k].enhanceTextfield({prompt:r[a+"Prompt"]})}submit=function(){var a=[],b;for(b=0;b<v;b++)a[b]=l[b].submit().val();
o.isValid()&&(e.submit.apply(this,a),p.dialog("close"))};h=d(p,l,{Create:submit,Update:submit,Remove:function(){e.remove();p.dialog("close")},Cancel:function(){p.dialog("close")}});return function(a){h.selectButtons(a);return h}}var e;f.fn.isValid.init();var r={linkTitle:"Link",insertImageTitle:"Image",uri:"Link",uriPrompt:"Enter or select link",title:"Title",titlePrompt:"Enter title",imageUri:"Image Source"};ME.dialog={link:j("link",[["title",{required:true}],["uri",{combobox:{key:"uri"},required:true}]]),
insertImage:j("insertImage",[["imageUri",{combobox:{key:"imageUri"},required:true}],["title"],["uri",{combobox:{key:"uri"}}]])}})(jQuery);
(function(){function f(a,c){var d=h.getParagraphs(a),e=d.length;for(i=0;i<e;i++)d[i]=c(d[i]);h.setParagraphs(a,d)}function d(a,c){var d=a.length,e,h,l;for(e=0;e<d;e++)h=a[e],/^\s*$/.test(h)||(h=h.match(/^((?:\w+\. )?(?: *[\*#] )?)\s*(.*)/),l=h[1],h=h[2],c(e,l,h))}function j(a,c,e){var t=h.extendSelection(a,c).split("\n");d(t,function(a,c,d){t[a]=e(c,d)});h.replaceSelection(a,t.join("\n"))}function e(a,c){var e=h.extendSelection(a,c).split("\n").slice(0,1);a.selectionEnd=a.selectionStart+e[0].length;
d(e,function(c,d,l){a.setSelectionRange(a.selectionStart+d.length,a.selectionEnd);e[c]=l});return e[0]}function r(a,c){f(a,function(a){var d,e,l=[];if(/^\w+\([^)]+\)\./.test(a)){d=jQuery.trim(a.slice(a.indexOf("(")+1,a.indexOf(")"))).split(/\s+/);e=d.length;for(i=0;i<e;i++)d[i]!="right"&&d[i]!="left"&&d[i]!="center"&&l.push(d[i]);l.push(c);return a.replace(/^(\w+)[^.]+.\s+/,"$1("+l.join(" ")+"). ")}else return/^\w+\./.test(a)?a.replace(/^(\w+)\.\s*/,"$1("+c+"). "):"p("+c+"). "+a})}function u(a,c){var d=
a.textArea.val(),e=c.exec(d);if(c.lastIndex!==0){for(;c.lastIndex<a.selectionStart;)e=c.exec(d);a.setSelectionRange(c.lastIndex-e[0].length,c.lastIndex);return e}}function s(a,c,d){j(a,"\n",function(a,e){/ on$/.test(c.className)||(e=d+" "+e);return e})}var p=jQuery,h,k={ul:"*",ol:"#"};h=ME.addMode("textile",{name:"Textile Mode",items:{"default":{clicked:function(a,c){var d,e=this;j(a," ",function(f,l){var b;/ on$/.test(c.className)?(b=(d=l.match(e.leftRegExp))?(d[1]||"")+l.slice(d[0].length):e.delimiter+
h.extendLeftSelection(a,/[ .]+/)+l,l=b,(d=l.match(e.rightRegExp))?l=l.slice(0,-d[0].length)+(d[1]||""):l+=h.extendRightSelection(a,/ +/)+e.delimiter):l=p.trim(e.delimiter+l)+e.delimiter;return f+l})}},bold:{delimiter:"*",leftRegExp:/^(\w+\. )?\s*\*/,rightRegExp:/\*([\.]*)$/},italic:{delimiter:"_",leftRegExp:/^(\w+\. )?\s*_/,rightRegExp:/_([\.]*)$/},alignLeft:{clicked:function(a){r(a,"left")}},alignRight:{clicked:function(a){r(a,"right")}},alignCenter:{clicked:function(a){r(a,"center")}},unorderedList:{clicked:function(a,
c){s(a,c,"*")}},orderedList:{clicked:function(a,c){s(a,c,"#")}},link:{clicked:function(a,c){var d,f,j,l;/ on$/.test(c.className)?(d=ME.dialog.link(["Update","Remove","Cancel"]),j=a.currentNodes.a.attributes.href,l=u(a,RegExp('"([^"]*)":'+j,"g")),f=l[1],d.val("input.uri",j)):(d=ME.dialog.link(["Create","Cancel"]),f=e(a," "));/^\s*$/.test(f)||d.val(".title",f);d.dialog("open",{submit:function(c,d){h.replaceSelection(a,'"'+c+'":'+d)},remove:function(){h.replaceSelection(a,l[1])},close:function(){h.updatePreview(a);
a.checkState()}})}},insertImage:{clicked:function(a,c){var d,f,j;if(/ on$/.test(c.className)){d=ME.dialog.insertImage(["Update","Remove","Cancel"]);j=a.currentNodes.img.attributes.src;u(a,RegExp("!"+j+"(\\([^\\)]*\\))?!(:[^ \n]*)?","g"));if(a.currentNodes.a)f=a.currentNodes.a.attributes.href;d.val("input.uri",f);d.val("input.imageUri",j);d.val("input.title",a.currentNodes.img.attributes.title)}else d=ME.dialog.insertImage(["Create","Cancel"]),e(a," ");d.dialog("open",{submit:function(c,d,e){d&&!/^\s*$/.test(d)&&
(c=c+"("+d+")");c="!"+c+"!";e&&!/^\s*$/.test(e)&&(c=c+":"+e);h.replaceSelection(a,c)},remove:function(){h.replaceSelection(a,"")},close:function(){h.updatePreview(a);a.checkState()}})}},formatBlock:{clicked:function(a,c){f(a,function(a){return/^\w+(\([\w ]+\))?\./.test(a)?a.replace(/^\w+(\([\w ]+\))?\.\s+/,c.value+"$1. "):/^[\*#] /.test(a)?a:c.value+". "+a})}}},updatePreview:function(a){var c=textileCompiler.compile(a.textArea.val());a.htmlDiv.html(c)},toText:function(a,c){function d(a,c){var e,f,
h={b:[/<(?:b|strong)>((.|[\r\n])*?)<\/(?:b|strong)>/gi,"*"],i:[/<(?:i|em)>((.|[\r\n])*?)<\/(?:i|em)>/gi,"_"],del:[/<(?:strike|del)>((.|[\r\n])*?)<\/(?:strike|del)>/gi,"-"],u:[/<(?:u|ins)>((.|[\r\n])*?)<\/(?:u|ins)>/gi,"+"]};for(e=a.length;e;e--)f=h[a[e-1]],c(f[0],f[1])}c||(c=a.htmlDiv.html());c=c.replace(/\s*<(ul|ol)>((.|[\r\n])*?)<\/\1>\s*/gi,function(a,c,e){a=c=="ul"?"*":"#";d(["b","i","u","del"],function(a,c){e=e.replace(a,c+"$1"+c)});return e.replace(/\s*<li>((.|[\r\n])*?)<\/li>\s*/gi,a+" $1\n")+
"\n"});c=c.replace(/ *<(p|h[1-4])([^>]*)>((.|[\r\n])*?)<\/\1>\s*/gi,function(a,c,e,f){a="";(e=e.match(/class=\"([^"]*)/))?a=c+"("+e[1]+"). ":c!="p"&&(a=c+". ");d(["b","i","u","del"],function(a,b){f=f.replace(a,function(a,g){return b+g.replace(/<br ?\/?>\s*/gi,b+"\n"+b)+b})});return a+f.replace(/<br ?\/?>\s*/gi,"\n")+"\n\n"});c=c.replace(/<img[^>]*>/gi,function(a){var c=p(a),a=c.attr("src");(c=c.attr("title"))&&!/^\s*$/.test(c)&&(a=a+"("+c+")");return"!"+a+"!"});c=c.replace(/<a href="([^\"]*)">((.|[\r\n])*?)<\/a>/gi,
function(a,c,d){return/^\s*![^!]+!\s*$/.test(d)?p.trim(d)+":"+c:'"'+d+'":'+c});c=c.replace(/\s*<code[^>]*>((.|[\r\n])*?)<\/code>\s*/gi," @$1@ ");c=c.replace(/(\r\n|\n){3,}/g,"\n\n");c=c.replace(/&nbsp;/g," ");return c=c.replace(/^[\r\n]+|[\r\n]+$/g,"")},getSelectionStates:function(a){var c=this.getSelection(a,"\n\n");return this.buildStateObject(textileCompiler.trace(c,a.selectionStart-a.boundaryStart,a.selectionEnd-a.boundaryStart),a.currentNodes={})},getParagraphs:function(a){return this.getSelection(a,
"\n\n").split(/\n\n+/)},setParagraphs:function(a,c){var d=a.textArea.val(),c=c.join("\n\n");a.rightBoundary===-1?a.textArea.val(d.slice(0,a.leftBoundary)+c):a.textArea.val(d.slice(0,a.leftBoundary)+c+d.slice(a.rightBoundary));this.moveCaret(a,c.length-a.boundaryDistance)},moveCaret:function(a,c){var d=a.selectionStart,e=a.startOfParagraphs;Math.abs(d-e)>Math.abs(c)?d+=c:d=e;a.textArea.focus();a.setSelectionRange(d,d)},pressed:function(a,c){switch(c){case 13:var d;var e=a.currentNodes.list;e&&/(u|o)l/i.test(e.tag)&&
(h.getSelection(a),d=ME.holdShift?" <br> ":"\n"+k[e.tag]+" ",h.replaceSelection(a,d,false),d=false);return d;default:this.prototype.pressed.apply(this,[c])}}})})();
(function(){function f(e){var e=e.exec(j),f,u;if(e)return f=/^\s*/.exec(e[0])[0].length,u=e[0].length,f&&d.advancePointer(f,true),u-f&&d.advancePointer(u-f),j=j.slice(u),e||true}var d=function(){function d(b,a){var c=["class"],g;x[b]&&(c=c.concat(x[b]));for(g=c.length;g--;)a(c[g])}function f(b){var c=true,g=a==-1,n,h,x;if(g)/(o|u)l/.test(k[0].tag)?(/(o|u)l/.test(b.tag)&&b.tag!=k[0].tag&&(b={tag:"p"}),n=k[0]=b):n=k[0];else for(h=a+1,x=k.length;h<x;h++)if(k[h].tag===b.tag){n=k[h];k[h]=k[a+1];k[a+1]=
n;break}n&&n.attributes&&d(n.tag,function(a){n.attributes[a]!==b.attributes[a]&&(c=false,delete n.attributes[a])});return n&&(g||c)}function j(b){this.tag=b.tag;this.attributes=b.attributes}function s(b){var a="";for(attr in b.attributes)b.attributes.hasOwnProperty(attr)&&(a+=" "+attr+'="'+b.attributes[attr]+'"');return"<"+b.tag+a+">"}function p(b){var a;for(a=h.length;a--;)if(h[a].tag===b)return a}var h,k,a,c,q,t,v,l,o,w,b=false,n,g=["li"],x={img:["title","src"],a:["href"]};return{init:function(){h=
[{content:""}]},initTrace:function(b,a,c){k=[];o=void 0;t=0;v=b;l=a;n=c},finalizeTrace:function(){o&&(o=w=false)},advancePointer:function(b,d){t+=b;if(o===void 0&&(t>v||t==n)){var e=h.length,f,x=0;c=o=true;for(f=1;f<e;f++)g.indexOf(h[f].tag)==-1?k[f-1-x]=new j(h[f]):x+=1;a=k.length-1}o&&t>l&&(w||d?o=w=false:w=true)},pushTag:function(d,e){var n={tag:d,attributes:e||{},content:""};h.push(n);o&&g.indexOf(d)==-1&&(c?(k[a+1]=new j(n),a+=1):k[a+1]&&(f(n)?a+=1:b=true))},closeTag:function(d){var e,n;d?(n=
p(d),e=h.splice(n,1)[0]):e=h.pop();o&&g.indexOf(d)==-1&&(c=false,b&&(k=k.slice(0,a+1),b=false),k[a].tag===e.tag&&(a-=1),q=true);this.pushString(s(e)+e.content,h[n-1]);this.pushString("</"+e.tag+">");q=false},popLineEnd:function(){for(var b=false,a={b:"*",i:"_"},c;"a,i,b,li".indexOf(h[h.length-1].tag)!=-1;)"li"===h[h.length-1].tag?(this.closeTag(),b=true):(c=h.pop(),this.pushString(a[c.tag]+c.content));return b},popParagraphEnd:function(){for(;h.length>1;)this.closeTag()},pushString:function(b,g){g||
(g=h[h.length-1]);g.content+=b;/^([ ]+|<br\/>)?$/.test(b)||(c&&(c=false),o&&!q&&k[a+1]&&(k=k.slice(0,a+1)))},isOpen:function(b){return typeof p(b)==="number"},blockTagIsOpen:function(){return!!h[1]},closeBlockTag:function(){for(;h[1];)this.closeTag()},getTrace:function(){return k},toHtml:function(){return h[0].content}}}(),j;textileCompiler={compile:function(e){d.init();for(j=e;!/^\s*$/.test(j);){if(e=f(/^\s*(h\d|p|bq)(\(([^#\)]*)(#[^\)]+)?\))?\. /)){var r={};e[3]&&(r["class"]=e[3]);if(e[4])r.id=
e[4];d.pushTag(e[1],r)}for(;!f(/^\n/)&&!/^\s*$/.test(j);){e=void 0;if(f(/^ *\* /))d.isOpen("ul")||(d.closeBlockTag(),d.pushTag("ul")),d.pushTag("li");else if(f(/^ *# /))d.isOpen("ol")||(d.closeBlockTag(),d.pushTag("ol")),d.pushTag("li");else{for(;d.isOpen("ul")||d.isOpen("ol");)d.closeTag();d.blockTagIsOpen()||d.pushTag("p")}e=f(/^ */);d.pushString(e[0]);for(e=e=void 0;;)if(f(/^_(?=[^ \n]+)/))d.isOpen("i")?d.pushString("_"):d.pushTag("i");else if(f(/^\*(?=[^ \n]+)/))d.isOpen("b")?d.pushString("*"):
d.pushTag("b");else if(e=f(/^([^ \n]+)_( +|(?=\n|$))/))d.isOpen("i")?(d.pushString(e[1]),d.closeTag("i"),d.pushString(e[2])):d.pushString(e[1]+"_"+e[2]);else if(e=f(/^([^ \n]+)\*( +|(?=\n|$))/))d.isOpen("b")?(d.pushString(e[1]),d.closeTag("b"),d.pushString(e[2])):d.pushString(e[1]+"*"+e[2]);else if(e=f(/^( *)"([^"]*)":([^ \n]+)/))d.pushString(e[1]),d.pushTag("a",{href:e[3]}),d.pushString(e[2]),d.closeTag();else if(e=f(/^( *)!([^!\(]+)(\(([^\)]*)\))?!(:([^ \n]+))?/)){d.pushString(e[1]);e[6]&&d.pushTag("a",
{href:e[6]});r={src:e[2]};if(e[4])r.title=e[4];d.pushTag("img",r);d.closeTag();e[6]&&d.closeTag()}else if(e=f(/^([^ \n]+)/))d.pushString(e[1]);else if(e=f(/^( +)/))d.pushString(e[1]);else{f(/^\n/);e=d.popLineEnd();!e&&!/^\s*(\n|$|[\*#] )/.test(j)&&d.pushString("<br/>");break}}d.popParagraphEnd()}return d.toHtml()},trace:function(e,f,j){d.initTrace(f,j,e.length);this.compile(e);d.finalizeTrace();return d.getTrace()}}})();
(function(){function f(b){return b.parent().is(".preview")?b:b.parentsUntil(".preview").last()}function d(){var b,a,c=-1;b=f(jQuery(o.getRangeAt(0).startContainer));a=f(jQuery(o.getRangeAt(0).endContainer))[0];return b[0]!==a?b.nextAll().filter(function(b){this==a&&(c=b);if(c===-1||c===b)return true}).add(b):b}function j(b){d().removeClass("left").removeClass("right").removeClass("center").addClass(b)}function e(b,a){var c=b[0],d;b.length>1?(d=b[b.length-1],w.setStart(c,0),w.setEnd(d,d.childNodes.length)):
w.selectNodeContents(c);a!==void 0&&w.collapse(a);o.removeAllRanges();o.addRange(w)}function r(b,a,c){/ on$/.test(a.className)?u(b):(a=v.getSelection(b,"br"),c=l("<"+c+">"),p(c,a.firstChild),h(b.leftBorder,c),h(b.rightBorder,c),v.replaceSelection(b,c))}function u(b){contents=v.getSelection(b,"li");lines=[];k(lines,contents.firstChild);$p=l("<p>").html(lines.join("<br>"));v.replaceSelection(b,$p)}function s(b,a,c){this.nextProperty=c;this.ancestors=b.parentsUntil(".preview");this.block=this.ancestors[this.ancestors.length-
1]||b[0];for(this.borderNode=this.ancestors[this.ancestors.length-2]||b[0];this.borderNode;){this.node=this.borderNode;if(!a||this.borderNode.nodeName.toLowerCase()===a)break;this.borderNode=this.borderNode[c]}this.safeBlock=this.borderNode?this.block:this.block[c]}function p(b,a){function c(){/^\s*$/.test(d.textContent)||b.append(d);d=document.createElement("li")}for(var d=document.createElement("li"),e;a!==null;)e=a.nextSibling,/br/i.test(a.nodeName)?c():/(p|h\d)/i.test(a.nodeName)?(c(),p(b,a.firstChild)):
/(o|u)l/i.test(a.nodeName)?(c(),l(a).children().appendTo(b)):/li/i.test(a.nodeName)?(c(),b.append(a)):d.appendChild(a),a=e;c()}function h(b,a){var c;if(b.safeBlock&&/ul/i.test(b.safeBlock.nodeName))next=b.safeBlock[b.nextProperty],c=l(b.safeBlock).remove().children(),b.nextProperty==="previousSibling"?c.prependTo(a):c.appendTo(a),b.safeBlock=next}function k(b,a){for(;a;)/(o|u)l/i.test(a.nodeName)?k(b,a.firstChild):/li/i.test(a.nodeName)&&b.push(a.innerHTML),a=a.nextSibling}function a(b){function a(b,
c){for(;!d[b];)d=d.parentNode;if((d=d[b])&&!/br|h\d|p/i.test(d.nodeName))return e([d],c),false}var c=o.getRangeAt(0),d,f;if(c.collapsed&&(d=c.startContainer,d.nodeType==3))if(f=d.nodeValue,c.startOffset+b===0&&/^ /.test(f))return a("previousSibling",false);else if(c.startOffset+b===d.length&&/ $/.test(f))return a("nextSibling",true)}function c(b,a){if(t(a,8)===false)return false;var c,d=true,f=b.currentNodes.block,h=b.currentNodes.list,f=(h||f).previousSibling,j=o.getRangeAt(0),k=j.startContainer;
if(!j.collapsed||!f||j.startOffset!==0)return true;for(;k.parentNode!==a[0];){if(k.previousSibling){d=false;if(/li/i.test(k.nodeName))c=true;else return true;break}k=k.parentNode}if(d){if(h)k=k.firstChild;k=l(k);c=k.contents();l(f).append(c);k.remove();e([c[0]],true)}else h&&c&&u(b);return false}function q(b,a){if(t(a,46)===false)return false;if(!l.browser.webkit)return true;var c,d=b.currentNodes.block;c=b.currentNodes.list;var d=(c||d).nextSibling,e=o.getRangeAt(0),f=e.startContainer;if(!e.collapsed||
!d||e.startOffset!==f.length)return true;for(;f.parentNode!==a[0];){if(f.nextSibling)return true;f=f.parentNode}if(c)f=f.lastChild;if(/(u|o)l/i.test(d.nodeName))d=d.firstChild;d=l(d);c=d.contents();l(f).append(c);d.remove();return false}function t(b,a,c){var d=o.getRangeAt(0);if(!l.browser.mozilla||c||d.collapsed||ME.util.isNeutralKey(a))return true;c=d.extractContents();if(b.is(":empty")||/^ *$/.test(b.text()))return c=document.createElement(c.childNodes[0].nodeName),b.html(c),e([c]),/^8|13|46$/.test(""+
a)?false:true}var v,l=jQuery,o=getSelection(),w=document.createRange();v=ME.addMode("wysiwyg",{name:"Preview Mode",items:{"default":{clicked:function(){document.execCommand(this.name,false,null)}},bold:{tag:"b"},italic:{tag:"i"},alignLeft:{clicked:function(){j("left")}},alignRight:{clicked:function(){j("right")}},alignCenter:{clicked:function(){j("center")}},unorderedList:{clicked:function(b,a){r(b,a,"ul")}},orderedList:{clicked:function(b,a){r(b,a,"ol")}},link:{clicked:function(b,a){var c,d,e,f=
o.getRangeAt(0),h={remove:function(){var b=d.text();d.replaceWith(b)},close:function(){b.htmlDiv.focus();b.checkState()}};/ on$/.test(a.className)?(d=l(b.currentNodes.a),c=ME.dialog.link(["Update","Remove","Cancel"]),h.submit=function(b,a){d.attr("href",a).text(b);f.selectNodeContents(d[0]);o.removeAllRanges();o.addRange(f)},e=d.text(),c.val("input.uri",d.attr("href"))):(c=ME.dialog.link(["Create","Cancel"]),h.submit=function(b,a){var c=l('<a href="'+a+'">'+b+"</a>")[0];f.deleteContents();f.insertNode(c);
f.selectNodeContents(c);o.removeAllRanges();o.addRange(f)},e=f.toString());/^\s*$/.test(e)||c.val(".title",e);c.dialog("open",h)}},insertImage:{clicked:function(b,a){var c,d,e=window.getSelection(),f=e.getRangeAt(0);/ on$/.test(a.className)?(c=ME.dialog.insertImage(["Update","Remove","Cancel"]),b.currentNodes.a&&(d=l(b.currentNodes.a),c.val("input.uri",d.attr("href")),f.selectNode(b.currentNodes.a)),imageNode=l(b.currentNodes.img),c.val("input.imageUri",imageNode.attr("src")),c.val("input.title",
imageNode.attr("title"))):c=ME.dialog.insertImage(["Create","Cancel"]);c.dialog("open",{submit:function(b,a,c){var d=b=l('<img src="'+b+'"/>');/^\s*$/.test(a)||b.attr({alt:a,title:a});/^\s*$/.test(c)||(d=l('<a href="'+c+'"/>').append(b));f.deleteContents();f.insertNode(d[0]);f.selectNode(b[0]);e.removeAllRanges();e.addRange(f)},remove:function(){imageNode.remove()},close:function(){b.htmlDiv.focus();b.checkState()}})}},formatBlock:{clicked:function(b,a){var c,f=[],h;d().replaceWith(function(){h=/(u|o)l/i.test(this.nodeName)?
this.nodeName:a.value;c=l("<"+h+">").addClass(this.className).append(this.childNodes);f.push(c[0]);return c});e(f)}}},getSelection:function(b,a){var c=o.getRangeAt(0);b.collapsed=c.collapsed;b.leftBorder=new s(jQuery(o.getRangeAt(0).startContainer),a,"previousSibling");b.rightBorder=new s(jQuery(o.getRangeAt(0).endContainer),a,"nextSibling");c.setStartBefore(b.leftBorder.node);c.setEndAfter(b.rightBorder.node);b.rightBorder.borderNode&&l(b.rightBorder.borderNode).nextAll().appendTo("<"+b.rightBorder.block.nodeName+
">").parent().insertAfter(b.rightBorder.block);return c.extractContents()},replaceSelection:function(b,a){b.leftBorder.safeBlock?a.insertAfter(b.leftBorder.safeBlock):b.htmlDiv.prepend(a);b.collapsed?e(a,true):e(a);/^\s*$/.test(b.leftBorder.block.textContent)&&l(b.leftBorder.block).remove();/^\s*$/.test(b.rightBorder.block.textContent)&&l(b.rightBorder.block).remove()},afterActivation:function(a){a.textArea.parent().hide();a.htmlDiv.attr("contentEditable",true);l.browser.mozilla&&document.execCommand("styleWithCSS",
null,false)},getSelectionStates:function(a){function c(a,b){if(b){var d=b.nodeName,e=a[0].nodeName;d!="#text"&&e!="#text"&&e!=d&&(a=a.find(b.nodeName.toLowerCase()))}return a.parentsUntil(".preview").add(a)}if(!l(document.activeElement).is(".preview"))return{};var d=[],e;e=o.getRangeAt(0).cloneContents().firstChild;d=c(jQuery(o.getRangeAt(0).startContainer),e);e=c(jQuery(o.getRangeAt(0).endContainer),e);/(u|o)l/i.test(d[0].nodeName)&&d[0].nodeName!==e[0].nodeName&&(d=d.toArray(),d[0]=l("<p>")[0]);
return this.buildStateObject(d,a.currentNodes={})},clicked:function(){a(0)},pressed:function(b,d){this.prototype.pressed.apply(this,[b,d]);switch(d){case 13:var f;var h=b.htmlDiv;if(t(h,13)===false)f=false;else{var j=true,k,p,r,s=editor.currentNodes.block;if(/h[1-5]/i.test(s.nodeName)){p=o.getRangeAt(0);for(k=r=p.endContainer;k.parentNode!==h[0];){if(k.nextSibling){j=false;break}k=k.parentNode}j&&p.endOffset===r.textContent.length&&(k=l("<p>").insertAfter(s),e(k),f=false)}}return f;case 8:return c(b,
b.htmlDiv);case 46:return q(b,b.htmlDiv);case 37:return a(-1);case 39:return a(1);default:return t(b.htmlDiv,d,this.holdNeutralKey)}},toText:function(a){return a.getDataMode().toText(a)},toHTML:function(a){return a.htmlDiv.html()}})})();
