ME=function(k){function d(a){k.extend(this,a)}function o(a){this.name=a}function b(a,c){this.name=a;this.options=c||[]}function h(a){var c=k('<div class="toolbar"></div>'),f=this;this.textArea=a.textArea;this.htmlDiv=a.htmlDiv;this.editor=a;this.div=c;for(item in j)j.hasOwnProperty(item)&&c.append(j[item].getButton());c.mouseup(function(c){c=c.target;if(!/(select|option)/i.test(c.nodeName)){if(/span/i.test(c.nodeName))c=c.parentNode;var e=c.className;e=e.split(" ")[0];f.runAction(e,c);a.checkState()}return!1}).change(function(a){a=
a.target;f.runAction(a.className,a);return!1});a.container.prepend(c)}function l(a){var c=this;this.loadedModes={};this.setDataType(a.attr("class"));if(this.dataType)this.textArea=a.bind("mouseup keyup",function(){c.checkState()}),this.htmlDiv=k('<div class="preview"></div>').bind("mouseup keyup",function(){c.is("wysiwyg")&&c.checkState()}),this.container=a.wrap('<div class="markupEditor"></div>').parent().append(c.htmlDiv),this.toolbar=new h(c)}function m(a,c,f){if(c)for(element in c)c.hasOwnProperty(element)&&
element!=="default"&&(j[element]||(j[element]=new a(element)),j[element][f]=k.extend({name:element},c["default"],c[element]))}var g={},e={},j={};d.prototype={load:function(a){this.editor=a;this.htmlDiv=a.htmlDiv;this.textArea=a.textArea;console.log("loaded Mode "+this.name)},getStates:k.noop,activate:function(){this.htmlDiv.is(":empty")?this.updatePreview():this.updateTextArea();this.afterActivation()},updatePreview:function(){console.log("updating preview in Mode "+this.name);this.htmlDiv.html(this.toHTML())},
updateTextArea:function(){console.log("updating TA in Mode "+this.name);this.textArea.val(this.toText())},afterActivation:function(){this.textArea.show();this.htmlDiv.attr("contentEditable",!1)},buildStateObject:function(a,c){for(var f,e=a.length,b={};e--;)switch(f=a[e],f.tag?f.tag:f.nodeName.toLowerCase()){case "a":c.a=f;b.link=!0;break;case "img":c.img=f;b.insertImage=!0;break;case "i":b.italic=!0;break;case "li":break;case "ol":b.insertOrderedList=!0;b.insertUnorderedList=!1;break;case "b":b.bold=
!0;break;case "ul":b.insertOrderedList=!1;b.insertUnorderedList=!0;break;default:b.formatBlock=f.tag?f.tag:f.nodeName.toLowerCase()}return b}};o.prototype={getButton:function(){return'<a href="#" class="'+this.name+'" ><span>'+this.name+"</span></a>"}};b.prototype={getButton:function(){var a=k('<select class="'+this.name+'"></select>'),c=this.options.length,f;a.className=this.name;for(f=0;f<c;f+=1)k("<option/>").val(this.options[f][0]).text(this.options[f][1]).appendTo(a);return a}};h.prototype={getDivSelection:function(){this.htmlDiv.focus();
theSelection=window.getSelection();theRange=theSelection.getRangeAt(0);return theRange.toString()},getTextAreaSelection:function(a){var c=this.textArea,f=c.val();c.focus();this.scrollPosition=c.scrollTop;this.selectionStart=c[0].selectionStart;this.selectionEnd=c[0].selectionEnd;if(a){a=Math.max(f.lastIndexOf(" ",this.selectionStart),f.lastIndexOf("\n",this.selectionStart));this.selectionStart=a!==-1?a+1:0;a=f.indexOf("\n",this.selectionEnd);c=a===-1?f.slice(this.selectionStart):f.slice(this.selectionStart,
a);a=0;do a=c.indexOf(" ",a+1);while(a!==-1&&this.selectionEnd>this.selectionStart+a);if(a===-1)a=c.length;this.selectionEnd=this.selectionStart+a}return this.selection=f.slice(this.selectionStart,this.selectionEnd)},replaceTextAreaSelection:function(a){var c=this.textArea,f=this.selectionStart;c.val(c.val().slice(0,this.selectionStart)+a+c.val().slice(this.selectionEnd,c.val().length));c[0].setSelectionRange(f,f+a.length);c.focus()},extendRightSelection:function(a){var c;a=RegExp(a.source,"g");a.lastIndex=
this.selectionEnd;if((c=a.exec(this.textArea.val()))&&a.lastIndex==this.selectionEnd+c[0].length)return this.selectionEnd+=c[0].length,c[0]},extendLeftSelection:function(a){var c=this.textArea.val().slice(0,this.selectionStart);a=RegExp(a.source+"$");if(a=a.exec(c))return this.selectionStart-=a[0].length,a[0]},replaceDivSelection:function(){},getSelection:function(a){return this.editor.is("wysiwyg")?this.getDivSelection(a):this.getTextAreaSelection(a)},replaceSelection:function(a){this.editor.is("wysiwyg")?
this.replaceDivSelection(a):this.replaceTextAreaSelection(a)},runAction:function(a,c){j[a][this.editor.currentMode.id].clicked(this,c);a!="changeMode"&&!this.editor.is("wysiwyg")&&this.editor.currentMode.updatePreview()},setActive:function(a){a&&this.div.children().each(function(){var c=this.className.split(" ")[0];a[c]===!0?this.className=c+" on":a[c]?this.value=a[c]:this.className=c})}};l.prototype={changeMode:function(a){if(!a||a===this.currentMode.id)return!1;a=this.getMode(a);this.commit();a.activate();
this.currentMode=a},getDataMode:function(){return this.getMode(this.dataType)},getMode:function(a){if(this.loadedModes[a])return this.loadedModes[a];else if(e[a])return this.loadedModes[a]=e[a](this),this.loadedModes[a];else console.log("Mode "+a+" is not defined")},setDataType:function(a){var c,f=a.split(/\s+/);for(a=0;a<f.length;a+=1)if(c=f[a],c!=="wysiwyg"&&e[c])this.dataType=c},commit:function(){this.is("wysiwyg")?this.getMode(this.dataType).updateTextArea():this.currentMode.updatePreview()},
is:function(a){return this.currentMode.id===a},checkState:function(){this.toolbar.setActive(this.currentMode.getStates())}};k.fn.initMarkupEditor=function(a){this.each(function(c,f){f=k(f);if(f.is("textarea")){var b=f,e;e={};k.extend(e,g,a);e=new l(b,e);e.currentMode=e.getDataMode();if(b.hasClass("wysiwyg"))e.currentMode=e.getMode("wysiwyg");e.currentMode.activate();e.toolbar.setActive({changeMode:e.currentMode.id})}});return this};j.changeMode=new b("changeMode");j.formatBlock=new b("formatBlock",
[["p","Paragraph"],["h1","Heading 1"],["h2","Heading 2"],["h3","Heading 3"]]);return{addMode:function(a,c){var f=c(),h=f.buttons,g=f.selects;f.id=a;m(o,h,a);m(b,g,a);j.changeMode.options.push([a,f.name]);j.changeMode[a]={clicked:function(a,c){a.editor.changeMode(c.value)}};e[a]=function(a){var c=new d(f);c.load(a);return c};return f}}}(jQuery);
ME.dialog=function(k){function d(d,l){fields=d.find(":input");d.dialog({autoOpen:!1,width:600,close:function(){b.close&&b.close();fields.not(":button, :submit, :reset").val("").removeAttr("checked").removeAttr("selected")}});return{dialog:function(m,g){g&&(b=g);d.dialog(m)},find:function(b){return d.find(b)},selectButtons:function(b){for(var g={},e=b.length;e--;)g[b[e]]=l[b[e]];d.dialog("option","buttons",g)},val:function(b,d){this.find(b).val(d)}}}function o(h,l){return function(m){var g,e,j=k("#"+
h+"-dialog");l=l(j);e=l.length;submit=function(){var a=[],c;for(c=0;c<e;c++)a[c]=l[c].val();b.submit.apply(this,a);j.dialog("close")};g=d(j,{Ok:submit,Update:submit,Remove:function(){b.remove();j.dialog("close")},Cancel:function(){j.dialog("close")}});this[h]=function(a){g.selectButtons(a);return g};return this[h](m)}}var b;return{link:o("link",function(b){return[b.find("input.title"),$uri=b.find("input.uri"),b.find("select.uri").change(function(){$uri.val(k(this).val())})]}),insertImage:o("insertImage",
function(b){return[b.find("input.imageUri"),b.find("input.title"),b.find("input.uri")]})}}(jQuery);$(document).ready(function(){$("textarea.markup").initMarkupEditor({})});
ME.addMode("textile",function(){function k(a,c){var f=a.editor.currentMode,b=f.getParagraphs(),e=b.length;for(i=0;i<e;i++)b[i]=c(b[i]);f.setParagraphs(b)}function d(a,c){k(a,function(a){var b,e,d=[];if(/^\w+\([^)]+\)\./.test(a)){b=jQuery.trim(a.slice(a.indexOf("(")+1,a.indexOf(")"))).split(/\s+/);e=b.length;for(i=0;i<e;i++)b[i]!="right"&&b[i]!="left"&&b[i]!="center"&&d.push(b[i]);d.push(c);return a.replace(/^(\w+)[^.]+.\s+/,"$1("+d.join(" ")+"). ")}else return/^\w+\./.test(a)?a.replace(/^(\w+)\.\s*/,
"$1("+c+"). "):"p("+c+"). "+a})}function o(a,c){match=c.exec(b);if(c.lastIndex!==0){for(;c.lastIndex<h;)match=c.exec(b);a.selectionStart=c.lastIndex-match[0].length;a.selectionEnd=c.lastIndex;return match}}var b,h,l,m,g,e={},j=jQuery;regexpes={"*":[/^(\w+\. )?\s*\*/,/\*([\.]*)$/],_:[/^(\w+\. )?\s*_/,/_([\.]*)$/]};return{name:"Textile Mode",buttons:{"default":{clicked:function(a,c){var b=a.getSelection(!0).split("\n"),e=b.length,d,n;for(d=0;d<e;d++)n=b[d],/^\s*$/.test(n)||(/ on$/.test(c.className)?
(n=(match=n.match(regexpes[this.delimiter][0]))?(match[1]||"")+n.slice(match[0].length):this.delimiter+a.extendLeftSelection(/[ .]+/)+n,(match=n.match(regexpes[this.delimiter][1]))?n=n.slice(0,-match[0].length)+(match[1]||""):n+=a.extendRightSelection(/ +/)+this.delimiter):n=j.trim(n.replace(/^(\w+\. )?\s*(.*)/,"$1"+this.delimiter+"$2"))+this.delimiter,b[d]=n);a.replaceSelection(b.join("\n"))}},bold:{delimiter:"*"},italic:{delimiter:"_"},alignLeft:{clicked:function(a){d(a,"left")}},alignRight:{clicked:function(a){d(a,
"right")}},alignCenter:{clicked:function(a){d(a,"center")}},link:{clicked:function(a,c){var b,d,j,n;/ on$/.test(c.className)?(b=ME.dialog.link(["Update","Remove","Cancel"]),j=e.a.attributes.href,n=o(a,RegExp('"([^"]*)":'+j,"g")),d=n[1],b.val("input.uri",j)):(b=ME.dialog.link(["Ok","Cancel"]),d=a.getSelection());/^\s*$/.test(d)||b.val(".title",d);b.dialog("open",{submit:function(c,b){a.replaceSelection('"'+c+'":'+b)},remove:function(){a.replaceSelection(n[1])},close:function(){a.editor.currentMode.updatePreview();
a.editor.checkState()}})}},insertImage:{clicked:function(a,c){var b,d,j;if(/ on$/.test(c.className)){b=ME.dialog.insertImage(["Update","Remove","Cancel"]);j=e.img.attributes.src;o(a,RegExp("!"+j+"(\\([^\\)]*\\))?!(:[^ \n]*)?","g"));if(e.a)d=e.a.attributes.href;b.val("input.uri",d);b.val("input.imageUri",j);b.val("input.title",e.img.attributes.title)}else b=ME.dialog.insertImage(["Ok","Cancel"]),a.getSelection();b.dialog("open",{submit:function(c,b,e){b&&!/^\s*$/.test(b)&&(c=c+"("+b+")");c="!"+c+"!";
e&&!/^\s*$/.test(e)&&(c=c+":"+e);a.replaceSelection(c)},remove:function(){a.replaceSelection("")},close:function(){a.editor.currentMode.updatePreview();a.editor.checkState()}})}}},selects:{formatBlock:{clicked:function(a,c){k(a,function(a){return/^\w+(\([\w ]+\))?\./.test(a)?a.replace(/^\w+(\([\w ]+\))?\.\s+/,c.value+"$1. "):c.value+". "+a})}}},updatePreview:function(){this.htmlDiv.html(textileCompiler.compile(this.textArea.val()))},toText:function(a){a||(a=this.htmlDiv.html());a=a.replace(/\s*<(h[1-4])>((.|[\r\n])*?)<\/\1>\s*/gi,
"\n\n$1. $2\n\n");a=a.replace(/\s*<(p)>((.|[\r\n])*?)<\/\1>\s*/gi,"\n\n$2\n\n");a=a.replace(/\s*<(p|h[1-4]).*class=\"([^\"]+)\">((.|[\r\n])*?)<\/\1>\s*/gi,"\n\n$1($2). $3\n\n");a=a.replace(/<br ?\/?>\s*/gi,"\n");a=a.replace(/<(?:b|strong)>((.|[\r\n])*?)<\/(?:b|strong)>/gi,"*$1*");a=a.replace(/<(?:i|em)>((.|[\r\n])*?)<\/(?:i|em)>/gi,"_$1_");a=a.replace(/<(?:strike|del)>((.|[\r\n])*?)<\/(?:strike|del)>/gi,"-$1-");a=a.replace(/<(?:u|ins)>((.|[\r\n])*?)<\/(?:u|ins)>/gi,"+$1+");a=a.replace(/<img[^>]*>/gi,
function(a){var b=j(a);a=b.attr("src");(b=b.attr("title"))&&!/^\s*$/.test(b)&&(a=a+"("+b+")");return"!"+a+"!"});a=a.replace(/<a href="([^\"]*)">((.|[\r\n])*?)<\/a>/gi,function(a,b,e){return/^\s*![^!]+!\s*$/.test(e)?j.trim(e)+":"+b:'"'+e+'":'+b});a=a.replace(/\s*<code[^>]*>((.|[\r\n])*?)<\/code>\s*/gi," @$1@ ");a=a.replace(/(\r\n|\n){3,}/g,"\n\n");return a=a.replace(/^[\r\n]+|[\r\n]+$/g,"")},getStates:function(){var a=this.getExtendedSelection();trace=textileCompiler.trace(a,h-l,selectionEnd-l);return this.buildStateObject(trace,
e={})},getExtendedSelection:function(){var a;a=0;h=this.textArea[0].selectionStart;selectionEnd=this.textArea[0].selectionEnd;b=this.textArea.val();l=0;for(m=-1;(a=b.indexOf("\n\n",a)+2)!==1;)if(h>a)l=a;else if(selectionEnd<a){m=a-2;break}a=m===-1?b.slice(l):b.slice(l,m);g=a.length;return a},getParagraphs:function(){return this.getExtendedSelection().split(/\n\n+/)},setParagraphs:function(a){a=a.join("\n\n");m===-1?this.textArea.val(b.slice(0,l)+a):this.textArea.val(b.slice(0,l)+a+b.slice(m));this.moveCaret(a.length-
g)},moveCaret:function(a){console.log("Moving caret: "+a);Math.abs(h-l)>Math.abs(a)?h+=a:h=l;this.textArea.focus();this.textArea[0].setSelectionRange(h,h)}}});
textileCompiler=function(){function k(b){b=b.exec(o);var h,l;if(b)return h=/^\s*/.exec(b[0])[0].length,l=b[0].length,h&&d.advancePointer(h),l-h&&d.advancePointer(l-h),o=o.slice(l),b||!0}var d=function(){function b(a,b){var c=["class"],e;definableAttributes[a]&&(c=c.concat(definableAttributes[a]));for(e=c.length;e--;)b(c[e])}function d(a){var c=!0,f=j==-1,g,h,l;if(f)g=e[0];else{h=j+1;for(l=e.length;h<l;h++)if(e[h].tag===a.tag){g=e[h];e[h]=e[j+1];e[j+1]=g;break}}g&&g.attributes&&b(g.tag,function(b){g.attributes[b]!==
a.attributes[b]&&(c=!1,delete g.attributes[b])});return g&&(f||c)}function l(a){var b="";for(attr in a.attributes)a.attributes.hasOwnProperty(attr)&&(b+=" "+attr+'="'+a.attributes[attr]+'"');return"<"+a.tag+b+">"}function k(a){var b;for(b=g.length;b--;)if(g[b].tag===a)return b}var g,e,j,a,c,f,o,r,n,p,q=!1;definableAttributes={img:["title","src"],a:["href"]};return{init:function(){g=[{content:""}]},initTrace:function(a,b){e=[];n=void 0;f=0;o=a;r=b},finalizeTrace:function(){n&&(n=p=!1)},advancePointer:function(b){f+=
b;if(n===void 0&&f>o){b=g.length;var c;a=n=!0;for(c=1;c<b;c++)e[c-1]={tag:g[c].tag,attributes:g[c].attributes};j=e.length-1}p?n=p=!1:n&&f>r&&(p=!0)},pushTag:function(b,c){var f={tag:b,attributes:c||{},content:""};g.push(f);n&&(a?(e[j+1]={tag:f.tag,attributes:f.attributes},j+=1):e[j+1]&&(d(f)?j+=1:q=!0))},closeTag:function(b){var d;b?(d=k(b),b=g.splice(d,1)[0]):b=g.pop();n&&(a=!1,q&&(e=e.slice(0,j+1),q=!1),e[j].tag===b.tag&&(j-=1),c=!0);this.pushString(l(b)+b.content,g[d-1]);this.pushString("</"+b.tag+
">");c=!1},popLineEnd:function(){for(var a=!1,b={b:"*",i:"_"},c;"a,i,b,li".indexOf(g[g.length-1].tag)!=-1;)"li"===g[g.length-1].tag?(this.closeTag(),a=!0):(c=g.pop(),this.pushString(b[c.tag]+c.content));return a},popParagraphEnd:function(){for(;g.length>1;)this.closeTag()},pushString:function(b,d){d||(d=g[g.length-1]);d.content+=b;/^([ ]+|<br\/>)?$/.test(b)||(a&&(a=!1),n&&!c&&e[j+1]&&(e=e.slice(0,j+1)))},isOpen:function(a){return typeof k(a)==="number"},getTrace:function(){return e},toHtml:function(){return g[0].content}}}(),
o;return{compile:function(b){d.init();for(o=b;!/^\s*$/.test(o);){if(b=k(/^\s*(h\d|p|bq)(\(([^#\)]*)(#[^\)]+)?\))?\. /)){var h={};b[3]&&(h["class"]=b[3]);if(b[4])h.id=b[4];d.pushTag(b[1],h)}else d.pushTag("p");for(;!k(/^\n/)&&!/^\s*$/.test(o);){if(k(/^ *\* /))d.isOpen("ul")||d.pushTag("ul"),d.pushTag("li");else if(k(/^ *# /))d.isOpen("ol")||d.pushTag("ol"),d.pushTag("li");else for(;d.isOpen("ul")||d.isOpen("ol");)d.closeTag();match=k(/^ */);d.pushString(match[0]);for(b=b=void 0;;)if(k(/^_(?=[^ \n]+)/))d.isOpen("i")?
d.pushString("_"):d.pushTag("i");else if(k(/^\*(?=[^ \n]+)/))d.isOpen("b")?d.pushString("*"):d.pushTag("b");else if(b=k(/^([^ \n]+)_( +|(?=\n|$))/))d.isOpen("i")?(d.pushString(b[1]),d.closeTag("i"),d.pushString(b[2])):d.pushString(b[1]+"_"+b[2]);else if(b=k(/^([^ \n]+)\*( +|(?=\n|$))/))d.isOpen("b")?(d.pushString(b[1]),d.closeTag("b"),d.pushString(b[2])):d.pushString(b[1]+"*"+b[2]);else if(b=k(/^( *)"([^"]*)":([^ \n]+)/))d.pushString(b[1]),d.pushTag("a",{href:b[3]}),d.pushString(b[2]),d.closeTag();
else if(b=k(/^( *)!([^!\(]+)(\(([^\)]*)\))?!(:([^ ]+))?/)){d.pushString(b[1]);b[6]&&d.pushTag("a",{href:b[6]});h={src:b[2]};if(b[4])h.title=b[4];d.pushTag("img",h);d.closeTag();b[6]&&d.closeTag()}else if(b=k(/^([^ \n]+)/))d.pushString(b[1]);else if(b=k(/^( +)/))d.pushString(b[1]);else{k(/^\n/);b=d.popLineEnd();!b&&!/^\s*(\n|$|[\*#] )/.test(o)&&d.pushString("<br/>");break}}d.popParagraphEnd()}return d.toHtml()},trace:function(b,h,l){d.initTrace(h,l);this.compile(b);d.finalizeTrace();return d.getTrace()}}}();
ME.addMode("wysiwyg",function(){function k(b){return b.parent().is(".preview")?b:b.parentsUntil(".preview").last()}function d(){var b,d,a=-1;b=k(jQuery(m.getRangeAt(0).startContainer));d=k(jQuery(m.getRangeAt(0).endContainer))[0];return b[0]!==d?b.nextAll().filter(function(b){this==d&&(a=b);if(a===-1||a===b)return!0}).add(b):b}function o(b){d().removeClass("left").removeClass("right").removeClass("center").addClass(b)}function b(b){var d=b[0];b.length>1?(b=b[b.length-1],g.setStart(d,0),g.setEnd(b,
b.childNodes.length)):g.selectNodeContents(d);m.removeAllRanges();m.addRange(g)}var h={},l=jQuery,m=getSelection(),g=document.createRange();return{name:"Preview Mode",buttons:{"default":{clicked:function(b,d){var a=m.getRangeAt(0),c;/ on$/.test(d.className)?document.execCommand(this.name,!1,null):(c=document.createElement(this.tag),a.surroundContents(c),m.removeAllRanges(),m.addRange(a))}},bold:{tag:"b"},italic:{tag:"i"},alignLeft:{clicked:function(){o("left")}},alignRight:{clicked:function(){o("right")}},
alignCenter:{clicked:function(){o("center")}},link:{clicked:function(b,d){var a,c,f,g=m.getRangeAt(0),k={remove:function(){var a=c.text();c.replaceWith(a)},close:function(){b.htmlDiv.focus();b.editor.checkState()}};/ on$/.test(d.className)?(c=l(h.a),a=ME.dialog.link(["Update","Remove","Cancel"]),k.submit=function(a,b){c.attr("href",b).text(a);g.selectNodeContents(c[0]);m.removeAllRanges();m.addRange(g)},f=c.text(),a.val("input.uri",c.attr("href"))):(a=ME.dialog.link(["Ok","Cancel"]),k.submit=function(a,
b){var c=l('<a href="'+b+'">'+a+"</a>")[0];g.deleteContents();g.insertNode(c);g.selectNodeContents(c);m.removeAllRanges();m.addRange(g)},f=g.toString());/^\s*$/.test(f)||a.val(".title",f);a.dialog("open",k)}},insertImage:{clicked:function(b,d){var a,c,f=window.getSelection(),g=f.getRangeAt(0);/ on$/.test(d.className)?(a=ME.dialog.insertImage(["Update","Remove","Cancel"]),h.a&&(c=l(h.a),a.val("input.uri",c.attr("href")),g.selectNode(h.a)),imageNode=l(h.img),a.val("input.imageUri",imageNode.attr("src")),
a.val("input.title",imageNode.attr("title"))):a=ME.dialog.insertImage(["Ok","Cancel"]);a.dialog("open",{submit:function(a,b,c){var d=a=l('<img src="'+a+'"/>');/^\s*$/.test(b)||a.attr({alt:b,title:b});/^\s*$/.test(c)||(d=l('<a href="'+c+'"/>').append(a));g.deleteContents();g.insertNode(d[0]);g.selectNode(a[0]);f.removeAllRanges();f.addRange(g)},remove:function(){imageNode.remove()},close:function(){b.htmlDiv.focus();b.editor.checkState()}})}}},selects:{formatBlock:{clicked:function(e,g){var a,c=[];
d().replaceWith(function(){a=l("<"+g.value+"></"+g.value+">").addClass(this.className).append(this.childNodes);c.push(a[0]);return a});b(c)}}},afterActivation:function(){this.textArea.hide();this.htmlDiv.attr("contentEditable",!0);jQuery.browser.mozilla&&document.execCommand("styleWithCSS",null,!1)},getStates:function(){if(l(document.activeElement).is(".preview")){var b=jQuery(m.getRangeAt(0).startContainer),d=m.getRangeAt(0).cloneContents().firstChild;d&&d.nodeName!="#text"&&b[0].nodeName!="#text"&&
(b=b.find(d.nodeName.toLowerCase()));return this.buildStateObject(b.parentsUntil(".preview").add(b),h={})}},toText:function(){return this.editor.getDataMode().toText()},toHTML:function(){return this.textArea.val()}}});
