(function(g){var d,k;k={check:function(){var h=!0;this.find(d.errorElement+"."+d.errorClass).remove();this.find(":input."+d.inputErrorClass).removeClass(d.inputErrorClass);this.find(":input.required").each(function(){var r=g(this),k=g.trim(r.val()),t=r.siblings("label").text().replace(d.removeLabelChar,""),n="";if(k==="")n=hasLabelPlaceholder?n=d.errorText.replace("{label}",t):n=d.errorText,h=!1;else if(r.hasClass("email")&&!/^([_a-z0-9-]+)(\.[_a-z0-9-]+)*@([a-z0-9-]+)(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/.test(k))n=
hasLabelPlaceholder?n=d.emailErrorText.replace("{label}",t):n=d.emailErrorText,h=!1;n!==""&&r.parent().addClass(d.errorClass)});return h},reset:function(){return this.find(":input.required").each(function(){g(this).parent().removeClass(d.errorClass)})}};g.fn.isValid=function(h){k[h]||(h="check");return k[h].apply(this,Array.prototype.slice.call(arguments,1))};g.fn.isValid.init=function(h){d=g.extend({},g.fn.isValid.defaults,h);hasLabelPlaceholder=d.errorText.indexOf("{label}")>-1};g.fn.isValid.defaults=
{errorClass:"error",errorText:"{label} is a required field.",emailErrorText:"Please enter a valid {label}",errorElement:"strong",removeLabelChar:"*"}})(jQuery);
(function(g){function d(a){g.extend(this,a);this.prototype=d.prototype}function k(a,c){this.name=a;if(c)this.clicked=c,s.push(a)}function h(a,c,f){k.apply(this,[a,f]);this.options=c||[]}function r(){var a,c,f;if(!q){a=0;for(c=p.length;a<c;a++)(f=m[p[a]])&&(q+=f.getButton())}return q}function u(a){var c=g('<div class="toolbar"></div>'),f=this;this.textArea=a.textArea;this.htmlDiv=a.htmlDiv;this.editor=a;this.div=c;c.html(r());c.mouseup(function(e){e=e.target;if(!/(select|option)/i.test(e.nodeName)){if(/span/i.test(e.nodeName))e=
e.parentNode;if(e.disabled)return a.is("wysiwyg")?a.htmlDiv.focus():a.textArea.focus(),!1;var b=e.className;b=b.split(" ")[0];f.runAction(b,e);a.checkState()}}).change(function(e){e=e.target;f.runAction(e.className,e);return!1}).click(function(){return!1});a.container.prepend(c)}function t(a,c){function f(b,c){b.keydown(function(b){if(c||e.is("wysiwyg"))return e.currentMode.pressed(b.keyCode)}).keyup(function(b){if(c||e.is("wysiwyg"))return e.currentMode.released(b.keyCode)}).mouseup(function(){if(c||
e.is("wysiwyg"))return e.currentMode.clicked()})}var e=this,b=0;this.loadedModes={};this.setDataType(a.attr("class"));this.settings=c;if(this.dataType)this.textArea=a.bind("mouseup keyup",function(){e.checkState();clearTimeout(b);b=setTimeout(function(){e.currentMode.updatePreview()},1E3)}),f(a,!0),this.htmlDiv=g('<div class="preview"></div>').bind("mouseup keyup",function(){e.is("wysiwyg")&&e.checkState()}),f(this.htmlDiv),this.container=a.wrap('<div class="markupEditor"></div>').parent().append(e.htmlDiv),
a.wrap('<div class="textarea">'),this.toolbar=new u(this)}function n(a,c){var f;f={};g.extend(f,j,c);f=new t(a,f);f.currentMode=f.getDataMode();if(a.hasClass("wysiwyg"))f.currentMode.activate(),f.currentMode=f.getMode("wysiwyg");f.currentMode.activate();f.checkState();return f}var j={},l={},m={},q="",p=["bold","italic","alignLeft","alignCenter","alignRight","unorderedList","orderedList","link","insertImage","save","wysiwyg","changeDataMode","formatBlock"],s=[];d.prototype={load:function(a){this.editor=
a;this.htmlDiv=a.htmlDiv;this.textArea=a.textArea;console.log("loaded Mode "+this.name)},pressed:function(a){if(a===16)this.holdShift=!0;if(ME.util.isNeutralKey(a))this.holdNeutralKey=!0},released:function(a){if(a===16)this.holdShift=!1;if(ME.util.isNeutralKey(a))this.holdNeutralKey=!1},clicked:g.noop,activate:function(){this.htmlDiv.is(":empty")?this.updatePreview():this.updateTextArea();this.editor.toolbar.loadModeToolbar();this.afterActivation()},updatePreview:function(){console.log("updating preview in Mode "+
this.name);this.htmlDiv.html(this.toHTML()||"<p>&nbsp;</p>")},updateTextArea:function(){console.log("updating TA in Mode "+this.name);this.textArea.val(this.toText())},afterActivation:function(){this.textArea.parent().show().find(":first-child").focus()[0].setSelectionRange(0,0);this.htmlDiv.attr("contentEditable",!1)},getStates:function(){var a=this.getSelectionStates();this.id==="wysiwyg"?a.wysiwyg=!0:a.changeDataMode=this.id;return a},getSelectionStates:function(){return{}},buildStateObject:function(a,
c){for(var f,e=a.length,b={};e--;)switch(f=a[e],f.tag?f.tag:f.nodeName.toLowerCase()){case "a":c.a=f;b.link=!0;break;case "img":c.img=f;b.insertImage=!0;break;case "i":b.italic=!0;break;case "b":b.bold=!0;break;case "ol":b.orderedList=!0;b.unorderedList=!1;b.formatBlock="disable";b.alignLeft="disable";b.alignRight="disable";b.alignCenter="disable";c.list=f;break;case "ul":b.orderedList=!1;b.unorderedList=!0;b.formatBlock="disable";b.alignLeft="disable";b.alignRight="disable";b.alignCenter="disable";
c.list=f;break;case "li":break;default:b.formatBlock=f.tag?f.tag:f.nodeName.toLowerCase(),c.block=f}return b},getSelection:function(a){var c=this.textArea,f=c.val(),e;c.focus();this.scrollPosition=c.scrollTop;this.selectionStart=c[0].selectionStart;this.selectionEnd=c[0].selectionEnd;f[this.selectionEnd-1]==="\n"&&(this.selectionEnd-=1);if(a){c=Math.max(f.lastIndexOf(a,this.selectionStart),f.lastIndexOf("\n",this.selectionStart));this.selectionStart=c!==-1?c+1:0;c=f.indexOf("\n",this.selectionEnd);
e=c===-1?f.slice(this.selectionStart):f.slice(this.selectionStart,c);c=0;do c=e.indexOf(a,c+1);while(c!==-1&&this.selectionEnd>this.selectionStart+c);if(c===-1)c=e.length;this.selectionEnd=this.selectionStart+c}return this.selection=f.slice(this.selectionStart,this.selectionEnd)},replaceSelection:function(a,c){var f=this.textArea,e=this.selectionStart,b=this.selectionStart+a.length;f.val(f.val().slice(0,this.selectionStart)+a+f.val().slice(this.selectionEnd,f.val().length));c===!0?b=e:c===!1&&(e=
b);f[0].setSelectionRange(e,b);f.focus()},extendRightSelection:function(a){var c;a=RegExp(a.source,"g");a.lastIndex=this.selectionEnd;if((c=a.exec(this.textArea.val()))&&a.lastIndex==this.selectionEnd+c[0].length)return this.selectionEnd+=c[0].length,c[0]},extendLeftSelection:function(a){var c=this.textArea.val().slice(0,this.selectionStart);a=RegExp(a.source+"$");if(a=a.exec(c))return this.selectionStart-=a[0].length,a[0]}};k.prototype={getButton:function(){return'<a href="#" class="'+this.name+
'" ><span>'+this.name+"</span></a>"}};h.prototype={getButton:function(){var a='<select class="'+this.name+'">',c=this.options.length,f;a.className=this.name;for(f=0;f<c;f+=1)a+='<option value="'+this.options[f][0]+'">'+this.options[f][1]+"</option>";return a+"</select>"}};u.prototype={loadModeToolbar:function(){var a=this.editor.currentMode.supportedItems,c=this.editor.settings.save,f=this.visibleItems,e=[];this.div.children().each(function(){var b=this.className;a.indexOf(b)!=-1&&(b!=="save"||c)?
((!f||f.indexOf(b)==-1)&&g(this).show(),e.push(b)):(!f||f.indexOf(b)!=-1)&&g(this).hide()});this.visibleItems=e},runAction:function(a,c){var f=m[a],e=this.editor,b=e.currentMode;(f[b.id]||f).clicked(e,b,c);a!="changeMode"&&!e.is("wysiwyg")&&b.updatePreview()},setActive:function(a){a&&this.div.children().each(function(){var c=this.className.split(" ")[0];if(a[c]=="disable")this.disabled=!0,this.className=c+" disabled";else if(this.disabled=!1,this.className=c,a[c]===!0)this.className=c+" on";else if(a[c])this.value=
a[c]})}};t.prototype={changeMode:function(a){a=this.getMode(a);this.commit();this.currentMode=a;a.activate()},changeDataMode:function(a){var c=this.is("wysiwyg");if(!a||a===this.currentMode.id)return!1;this.changeMode(a);c&&this.changeMode("wysywyg")},getDataMode:function(){return this.getMode(this.dataType)},getMode:function(a){if(this.loadedModes[a])return this.loadedModes[a];else if(l[a])return this.loadedModes[a]=l[a](this),this.loadedModes[a];else console.log("Mode "+a+" is not defined")},setDataType:function(a){var c,
f=a.split(/\s+/);for(a=0;a<f.length;a+=1)if(c=f[a],c!=="wysiwyg"&&l[c])this.dataType=c},commit:function(){this.is("wysiwyg")?this.getMode(this.dataType).updateTextArea():this.currentMode.updatePreview()},is:function(a){return this.currentMode.id===a},checkState:function(){this.toolbar.setActive(this.currentMode.getStates())}};ME={addMode:function(a,c){var f=c(),e=f.items,b,o=s.slice();f.id=a;if(e)for(item in e)e.hasOwnProperty(item)&&item!=="default"&&(o.push(item),m[item]||(b=e[item].options?h:k,
m[item]=new b(item)),m[item][a]=g.extend({name:item},e["default"],e[item]));a!=="wysiwyg"&&m.changeDataMode.options.push([a,f.name]);f.supportedItems=o;l[a]=function(b){var e=new d(f);e.load(b);return e};return f},options:{},setOptions:function(a){this.options=a}};g.fn.initMarkupEditor=function(a){ME.settings=a;this.each(function(c,f){var e=g(f);if(e.is("textarea"))n(e,a);else{e.css("min-height",e.height());var b;b=g('<textarea class="'+e[0].className+'">').prependTo(e);b=n(b,a);b.htmlDiv.append(b.container.nextAll());
b.currentMode.updateTextArea();b.changeMode("wysiwyg");b.checkState();e.append(b.container)}});return this};m.changeDataMode=new h("changeDataMode",[],function(a,c,f){a.changeDataMode(f.value)});m.formatBlock=new h("formatBlock",[["p","Paragraph"],["h1","Heading 1"],["h2","Heading 2"],["h3","Heading 3"]]);m.save=new k("save",function(a){a.commit();a.settings.save(a)});m.wysiwyg=new k("wysiwyg",function(a){a.is("wysiwyg")?a.changeMode(a.dataType):a.changeMode("wysiwyg")});return ME})(jQuery);
(function(g){neutralKeys="9.16.17.18.20.27.33.34.35.36.37.38.39.40.45.91.93.93";g.util={isNeutralKey:function(d){return neutralKeys.indexOf(""+d)!=-1},isRemovalKey:function(d){return d==46||d==8}}})(ME);
(function(g,d){var k=d.util.isNeutralKey,h=d.util.isRemovalKey;g.fn.enhanceTextfield=function(d){d=d||{};return this.each(function(){function u(){j.css("color","grey").data("hasPrompt",!0).val(d.prompt)}function t(){j.css("color",q).data("hasPrompt",!1).val("")}function n(){j.val()&&j.val()!==d.prompt?(j.css("color",q),l.show()):(u(),l.hide(),m=!1)}var j=g(this),l,m,q=j.css("color");j.is("input")&&(l=g("<span>x</span>").click(function(){t();j.focus();l.hide();m=!1}),$p=j.wrap('<span class="clearButton">').focus(function(){!m&&
j.val()===d.prompt&&t();j.parent().addClass("focus")}).focusout(function(){!m&&!j.val()&&u();j.parent().removeClass("focus")}).keydown(function(g){!k(g.which)&&(!m||h(g.which))&&j.val()===d.prompt&&t()}).keyup(function(d){!m&&!k(d.which)&&!h(d.which)&&(m=!0,n())}).bind("blur change",function(){n()}).submit(function(){j.val()===d.prompt&&t()}).parent().append(l),j.hasClass("ui-corner-left")?$p.addClass("ui-corner-left"):$p.addClass("ui-corner-all"))})}})(jQuery,ME);
(function(g,d){g.fn.required=function(d){return this.each(function(){d?g(this).addClass("required"):g(this).removeClass("required")})};g.widget("ui.combobox",{_create:function(){var k=this.element,h=this.options.key,r=g.ui.autocomplete.escapeRegex;k.autocomplete({delay:0,minLength:0,source:function(g,k){var n=RegExp(r(g.term),"i"),j=d.options[h]||[],l=j.length,m=[],q,p;if(g.term)for(p=0;p<l;p++)q=j[p],n.test(q)&&m.push({label:q.replace(RegExp("(?![^&;]+;)(?!<[^<>]*)("+r(g.term)+")(?![^<>]*>)(?![^&;]+;)",
"gi"),"<strong>$1</strong>"),value:q});else m=j;k(m)},focus:function(d,h){k.val(h.item.value).change()}}).addClass("ui-corner-left");k.data("autocomplete")._renderItem=function(d,h){return g("<li></li>").data("item.autocomplete",h).append("<a>"+h.label+"</a>").appendTo(d)};this.button=g("<button type='button'>&nbsp;</button>").attr("tabIndex",-1).attr("title","Show All Items").insertAfter(k).button({icons:{primary:"ui-icon-triangle-1-s"},text:!1}).removeClass("ui-corner-all").addClass("ui-corner-right ui-button-icon").click(function(){k.autocomplete("widget").is(":visible")?
k.autocomplete("close"):(k.data("hasPrompt")&&k.val(""),k.autocomplete("search",""),k.focus())})},destroy:function(){this.button.remove();g.Widget.prototype.destroy.call(this)}})})(jQuery,ME);
(function(g){function d(d,g,k){var j=g.length,l=d.find(":first-child");d.dialog({autoOpen:!1,width:600,close:function(){h.close&&h.close();for(i=0;i<j;i++)g[i].val("").removeAttr("checked").removeAttr("selected")},open:function(){for(i=0;i<j;i++)g[i].change();g[0][0].setSelectionRange(0,0);l.isValid("reset")}});return{dialog:function(g,j){j&&(h=j);d.dialog(g)},find:function(h){return d.find(h)},selectButtons:function(h){for(var g={},j=h.length;j--;)g[h[j]]=k[h[j]];d.dialog("option","buttons",g)},
val:function(d,h){this.find(d).val(h)}}}function k(k,t){var n,j,l,m,q,p,s,a=t.length,c=[];n=g('<div id="'+k+'-dialog" title="'+r[k+"Title"]+'"><form>');var f=n.find(":first-child");for(l=0;l<a;l++){m=t[l][0];q=t[l][1];f.append('<label for="'+m+'">'+r[m]+"</label>");c[l]=g('<input type="text" class="'+m+'" name="'+m+'">').appendTo(f);if(q)for(p in q)q.hasOwnProperty(p)&&(s=q[p],c[l][p](s));c[l].enhanceTextfield({prompt:r[m+"Prompt"]})}submit=function(){var e=[],b;for(b=0;b<a;b++)e[b]=c[b].submit().val();
f.isValid()&&(h.submit.apply(this,e),n.dialog("close"))};j=d(n,c,{Create:submit,Update:submit,Remove:function(){h.remove();n.dialog("close")},Cancel:function(){n.dialog("close")}});return function(e){j.selectButtons(e);return j}}var h;g.fn.isValid.init();var r={linkTitle:"Link",insertImageTitle:"Image",uri:"Link",uriPrompt:"Enter or select link",title:"Title",titlePrompt:"Enter title",imageUri:"Image Source"};ME.dialog={link:k("link",[["title",{required:!0}],["uri",{combobox:{key:"uri"},required:!0}]]),
insertImage:k("insertImage",[["imageUri",{combobox:{key:"imageUri"},required:!0}],["title"],["uri",{combobox:{key:"uri"}}]])}})(jQuery);
ME.addMode("textile",function(){function g(c,a){var e=c.getParagraphs(),b=e.length;for(i=0;i<b;i++)e[i]=a(e[i]);c.setParagraphs(e)}function d(c,a){var e=c.length,b,o,v;for(b=0;b<e;b++)o=c[b],/^\s*$/.test(o)||(o=o.match(/^((?:\w+\. )?(?: *[\*#] )?)\s*(.*)/),v=o[1],o=o[2],a(b,v,o))}function k(c,a,e){var b=c.getSelection(a).split("\n");d(b,function(c,a,f){b[c]=e(a,f)});c.replaceSelection(b.join("\n"))}function h(c){var a=c.getSelection("\n").split("\n").slice(0,1);c.selectionEnd=c.selectionStart+a[0].length;
d(a,function(e,b,o){c.selectionStart+=b.length;a[e]=o});return a[0]}function r(c,a){g(c,function(e){var b,c,d=[];if(/^\w+\([^)]+\)\./.test(e)){b=jQuery.trim(e.slice(e.indexOf("(")+1,e.indexOf(")"))).split(/\s+/);c=b.length;for(i=0;i<c;i++)b[i]!="right"&&b[i]!="left"&&b[i]!="center"&&d.push(b[i]);d.push(a);return e.replace(/^(\w+)[^.]+.\s+/,"$1("+d.join(" ")+"). ")}else return/^\w+\./.test(e)?e.replace(/^(\w+)\.\s*/,"$1("+a+"). "):"p("+a+"). "+e})}function u(c,a){var e=a.exec(n);if(a.lastIndex!==0){for(;a.lastIndex<
j;)e=a.exec(n);c.selectionStart=a.lastIndex-e[0].length;c.selectionEnd=a.lastIndex;return e}}function t(c,a,e){k(c,"\n",function(b,c){/ on$/.test(a.className)||(c=e+" "+c);return c})}var n,j,l,m,q,p={},s=jQuery,a={ul:"*",ol:"#"};regexpes={"*":[/^(\w+\. )?\s*\*/,/\*([\.]*)$/],_:[/^(\w+\. )?\s*_/,/_([\.]*)$/]};return{name:"Textile Mode",items:{"default":{clicked:function(c,a,e){var b,o=this;k(a," ",function(c,d){/ on$/.test(e.className)?(d=(b=d.match(regexpes[o.delimiter][0]))?(b[1]||"")+d.slice(b[0].length):
o.delimiter+a.extendLeftSelection(/[ .]+/)+d,(b=d.match(regexpes[o.delimiter][1]))?d=d.slice(0,-b[0].length)+(b[1]||""):d+=a.extendRightSelection(/ +/)+o.delimiter):d=s.trim(o.delimiter+d)+o.delimiter;return c+d})}},bold:{delimiter:"*"},italic:{delimiter:"_"},alignLeft:{clicked:function(c,a){r(a,"left")}},alignRight:{clicked:function(c,a){r(a,"right")}},alignCenter:{clicked:function(c,a){r(a,"center")}},unorderedList:{clicked:function(c,a,e){t(a,e,"*")}},orderedList:{clicked:function(c,a,e){t(a,e,
"#")}},link:{clicked:function(a,d,e){var b,o,v;/ on$/.test(e.className)?(e=ME.dialog.link(["Update","Remove","Cancel"]),o=p.a.attributes.href,v=u(d,RegExp('"([^"]*)":'+o,"g")),b=v[1],e.val("input.uri",o)):(e=ME.dialog.link(["Create","Cancel"]),b=h(d));/^\s*$/.test(b)||e.val(".title",b);e.dialog("open",{submit:function(b,e){d.replaceSelection('"'+b+'":'+e)},remove:function(){d.replaceSelection(v[1])},close:function(){d.updatePreview();a.checkState()}})}},insertImage:{clicked:function(a,d,e){var b,
o;if(/ on$/.test(e.className)){e=ME.dialog.insertImage(["Update","Remove","Cancel"]);o=p.img.attributes.src;u(d,RegExp("!"+o+"(\\([^\\)]*\\))?!(:[^ \n]*)?","g"));if(p.a)b=p.a.attributes.href;e.val("input.uri",b);e.val("input.imageUri",o);e.val("input.title",p.img.attributes.title)}else e=ME.dialog.insertImage(["Create","Cancel"]),h(d);e.dialog("open",{submit:function(b,e,a){e&&!/^\s*$/.test(e)&&(b=b+"("+e+")");b="!"+b+"!";a&&!/^\s*$/.test(a)&&(b=b+":"+a);d.replaceSelection(b)},remove:function(){d.replaceSelection("")},
close:function(){d.updatePreview();a.checkState()}})}},formatBlock:{clicked:function(a,d,e){g(d,function(b){return/^\w+(\([\w ]+\))?\./.test(b)?b.replace(/^\w+(\([\w ]+\))?\.\s+/,e.value+"$1. "):/^[\*#] /.test(b)?b:e.value+". "+b})}}},updatePreview:function(){this.htmlDiv.html(textileCompiler.compile(this.textArea.val()))},toText:function(a){function d(a,b){var c,f,h={b:[/<(?:b|strong)>((.|[\r\n])*?)<\/(?:b|strong)>/gi,"*"],i:[/<(?:i|em)>((.|[\r\n])*?)<\/(?:i|em)>/gi,"_"],del:[/<(?:strike|del)>((.|[\r\n])*?)<\/(?:strike|del)>/gi,
"-"],u:[/<(?:u|ins)>((.|[\r\n])*?)<\/(?:u|ins)>/gi,"+"]};for(c=a.length;c;c--)f=h[a[c-1]],b(f[0],f[1])}a||(a=this.htmlDiv.html());a=a.replace(/\s*<(ul|ol)>((.|[\r\n])*?)<\/\1>\s*/gi,function(a,b,c){a=b=="ul"?"*":"#";d(["b","i","u","del"],function(a,b){c=c.replace(a,b+"$1"+b)});return c.replace(/\s*<li>((.|[\r\n])*?)<\/li>\s*/gi,a+" $1\n")+"\n"});a=a.replace(/ *<(p|h[1-4])([^>]*)>((.|[\r\n])*?)<\/\1>\s*/gi,function(a,b,c,h){a="";(c=c.match(/class=\"([^"]*)/))?a=b+"("+c[1]+"). ":b!="p"&&(a=b+". ");
d(["b","i","u","del"],function(a,b){h=h.replace(a,function(a,e){return b+e.replace(/<br ?\/?>\s*/gi,b+"\n"+b)+b})});return a+h.replace(/<br ?\/?>\s*/gi,"\n")+"\n\n"});a=a.replace(/<img[^>]*>/gi,function(a){var b=s(a);a=b.attr("src");(b=b.attr("title"))&&!/^\s*$/.test(b)&&(a=a+"("+b+")");return"!"+a+"!"});a=a.replace(/<a href="([^\"]*)">((.|[\r\n])*?)<\/a>/gi,function(a,b,c){return/^\s*![^!]+!\s*$/.test(c)?s.trim(c)+":"+b:'"'+c+'":'+b});a=a.replace(/\s*<code[^>]*>((.|[\r\n])*?)<\/code>\s*/gi," @$1@ ");
a=a.replace(/(\r\n|\n){3,}/g,"\n\n");a=a.replace(/&nbsp;/g," ");return a=a.replace(/^[\r\n]+|[\r\n]+$/g,"")},getSelectionStates:function(){var a=this.getExtendedSelection();trace=textileCompiler.trace(a,j-l,selectionEnd-l);return this.buildStateObject(trace,p={})},getExtendedSelection:function(){var a;a=0;j=this.textArea[0].selectionStart;selectionEnd=this.textArea[0].selectionEnd;n=this.textArea.val();l=0;for(m=-1;(a=n.indexOf("\n\n",a)+2)!==1;)if(j>a)l=a;else if(selectionEnd<a){m=a-2;break}a=m===
-1?n.slice(l):n.slice(l,m);q=a.length;return a},getParagraphs:function(){return this.getExtendedSelection().split(/\n\n+/)},setParagraphs:function(a){a=a.join("\n\n");m===-1?this.textArea.val(n.slice(0,l)+a):this.textArea.val(n.slice(0,l)+a+n.slice(m));this.moveCaret(a.length-q)},moveCaret:function(a){Math.abs(j-l)>Math.abs(a)?j+=a:j=l;this.textArea.focus();this.textArea[0].setSelectionRange(j,j)},pressed:function(c){switch(c){case 13:var d;if((c=p.list)&&/(u|o)l/i.test(c.tag))this.getSelection(),
d=this.holdShift?" <br> ":"\n"+a[c.tag]+" ",this.replaceSelection(d,!1),d=!1;return d;default:this.prototype.pressed.apply(this,[c])}}}});
(function(){function g(h){h=h.exec(k);var g,u;if(h)return g=/^\s*/.exec(h[0])[0].length,u=h[0].length,g&&d.advancePointer(g,!0),u-g&&d.advancePointer(u-g),k=k.slice(u),h||!0}var d=function(){function d(a,b){var e=["class"],c;w[a]&&(e=e.concat(w[a]));for(c=e.length;c--;)b(e[c])}function g(a){var b=!0,e=m==-1,c,o,f;if(e)/(o|u)l/.test(l[0].tag)?(/(o|u)l/.test(a.tag)&&a.tag!=l[0].tag&&(a={tag:"p"}),c=l[0]=a):c=l[0];else{o=m+1;for(f=l.length;o<f;o++)if(l[o].tag===a.tag){c=l[o];l[o]=l[m+1];l[m+1]=c;break}}c&&
c.attributes&&d(c.tag,function(e){c.attributes[e]!==a.attributes[e]&&(b=!1,delete c.attributes[e])});return c&&(e||b)}function k(a){this.tag=a.tag;this.attributes=a.attributes}function t(a){var b="";for(attr in a.attributes)a.attributes.hasOwnProperty(attr)&&(b+=" "+attr+'="'+a.attributes[attr]+'"');return"<"+a.tag+b+">"}function n(a){var b;for(b=j.length;b--;)if(j[b].tag===a)return b}var j,l,m,q,p,s,a,c,f,e,b=!1,o,v=["li"],w={img:["title","src"],a:["href"]};return{init:function(){j=[{content:""}]},
initTrace:function(b,e,d){l=[];f=void 0;s=0;a=b;c=e;o=d},finalizeTrace:function(){f&&(f=e=!1)},advancePointer:function(b,d){s+=b;if(f===void 0&&(s>a||s==o)){var h=j.length,g,w=0;q=f=!0;for(g=1;g<h;g++)v.indexOf(j[g].tag)==-1?l[g-1-w]=new k(j[g]):w+=1;m=l.length-1}f&&s>c&&(e||d?f=e=!1:e=!0)},pushTag:function(a,e){var c={tag:a,attributes:e||{},content:""};j.push(c);f&&v.indexOf(a)==-1&&(q?(l[m+1]=new k(c),m+=1):l[m+1]&&(g(c)?m+=1:b=!0))},closeTag:function(a){var e,c;a?(c=n(a),e=j.splice(c,1)[0]):e=
j.pop();f&&v.indexOf(a)==-1&&(q=!1,b&&(l=l.slice(0,m+1),b=!1),l[m].tag===e.tag&&(m-=1),p=!0);this.pushString(t(e)+e.content,j[c-1]);this.pushString("</"+e.tag+">");p=!1},popLineEnd:function(){for(var a=!1,b={b:"*",i:"_"},e;"a,i,b,li".indexOf(j[j.length-1].tag)!=-1;)"li"===j[j.length-1].tag?(this.closeTag(),a=!0):(e=j.pop(),this.pushString(b[e.tag]+e.content));return a},popParagraphEnd:function(){for(;j.length>1;)this.closeTag()},pushString:function(a,b){b||(b=j[j.length-1]);b.content+=a;/^([ ]+|<br\/>)?$/.test(a)||
(q&&(q=!1),f&&!p&&l[m+1]&&(l=l.slice(0,m+1)))},isOpen:function(a){return typeof n(a)==="number"},blockTagIsOpen:function(){return!!j[1]},closeBlockTag:function(){for(;j[1];)this.closeTag()},getTrace:function(){return l},toHtml:function(){return j[0].content}}}(),k;textileCompiler={compile:function(h){d.init();for(k=h;!/^\s*$/.test(k);){if(h=g(/^\s*(h\d|p|bq)(\(([^#\)]*)(#[^\)]+)?\))?\. /)){var r={};h[3]&&(r["class"]=h[3]);if(h[4])r.id=h[4];d.pushTag(h[1],r)}for(;!g(/^\n/)&&!/^\s*$/.test(k);){h=void 0;
if(g(/^ *\* /))d.isOpen("ul")||(d.closeBlockTag(),d.pushTag("ul")),d.pushTag("li");else if(g(/^ *# /))d.isOpen("ol")||(d.closeBlockTag(),d.pushTag("ol")),d.pushTag("li");else{for(;d.isOpen("ul")||d.isOpen("ol");)d.closeTag();d.blockTagIsOpen()||d.pushTag("p")}h=g(/^ */);d.pushString(h[0]);for(h=h=void 0;;)if(g(/^_(?=[^ \n]+)/))d.isOpen("i")?d.pushString("_"):d.pushTag("i");else if(g(/^\*(?=[^ \n]+)/))d.isOpen("b")?d.pushString("*"):d.pushTag("b");else if(h=g(/^([^ \n]+)_( +|(?=\n|$))/))d.isOpen("i")?
(d.pushString(h[1]),d.closeTag("i"),d.pushString(h[2])):d.pushString(h[1]+"_"+h[2]);else if(h=g(/^([^ \n]+)\*( +|(?=\n|$))/))d.isOpen("b")?(d.pushString(h[1]),d.closeTag("b"),d.pushString(h[2])):d.pushString(h[1]+"*"+h[2]);else if(h=g(/^( *)"([^"]*)":([^ \n]+)/))d.pushString(h[1]),d.pushTag("a",{href:h[3]}),d.pushString(h[2]),d.closeTag();else if(h=g(/^( *)!([^!\(]+)(\(([^\)]*)\))?!(:([^ \n]+))?/)){d.pushString(h[1]);h[6]&&d.pushTag("a",{href:h[6]});r={src:h[2]};if(h[4])r.title=h[4];d.pushTag("img",
r);d.closeTag();h[6]&&d.closeTag()}else if(h=g(/^([^ \n]+)/))d.pushString(h[1]);else if(h=g(/^( +)/))d.pushString(h[1]);else{g(/^\n/);h=d.popLineEnd();!h&&!/^\s*(\n|$|[\*#] )/.test(k)&&d.pushString("<br/>");break}}d.popParagraphEnd()}return d.toHtml()},trace:function(h,g,k){d.initTrace(g,k,h.length);this.compile(h);d.finalizeTrace();return d.getTrace()}}})();
ME.addMode("wysiwyg",function(){function g(a){return a.parent().is(".preview")?a:a.parentsUntil(".preview").last()}function d(){var a,b,d=-1;a=g(jQuery(c.getRangeAt(0).startContainer));b=g(jQuery(c.getRangeAt(0).endContainer))[0];return a[0]!==b?a.nextAll().filter(function(a){this==b&&(d=a);if(d===-1||d===a)return!0}).add(a):a}function k(a){d().removeClass("left").removeClass("right").removeClass("center").addClass(a)}function h(a,b){var d=a[0],h;a.length>1?(h=a[a.length-1],f.setStart(d,0),f.setEnd(h,
h.childNodes.length)):f.selectNodeContents(d);b!==void 0&&f.collapse(b);c.removeAllRanges();c.addRange(f)}function r(e,b,c,d){/ on$/.test(c.className)?u(e,b):(c=b.getSelection("br"),d=a("<"+d+">"),n(d,c.firstChild),j(b.leftBorder,d),j(b.rightBorder,d),b.replaceSelection(e,d))}function u(e,b){contents=b.getSelection("li");lines=[];l(lines,contents.firstChild);$p=a("<p>").html(lines.join("<br>"));b.replaceSelection(e,$p)}function t(a,b,c){this.nextProperty=c;this.ancestors=a.parentsUntil(".preview");
this.block=this.ancestors[this.ancestors.length-1]||a[0];for(this.borderNode=this.ancestors[this.ancestors.length-2]||a[0];this.borderNode;){this.node=this.borderNode;if(!b||this.borderNode.nodeName.toLowerCase()===b)break;this.borderNode=this.borderNode[c]}this.safeBlock=this.borderNode?this.block:this.block[c]}function n(e,b){function c(){/^\s*$/.test(d.textContent)||e.append(d);d=document.createElement("li")}for(var d=document.createElement("li"),h;b!==null;)h=b.nextSibling,/br/i.test(b.nodeName)?
c():/(p|h\d)/i.test(b.nodeName)?(c(),n(e,b.firstChild)):/(o|u)l/i.test(b.nodeName)?(c(),a(b).children().appendTo(e)):/li/i.test(b.nodeName)?(c(),e.append(b)):d.appendChild(b),b=h;c()}function j(e,b){var c;if(e.safeBlock&&/ul/i.test(e.safeBlock.nodeName))next=e.safeBlock[e.nextProperty],c=a(e.safeBlock).remove().children(),e.nextProperty==="previousSibling"?c.prependTo(b):c.appendTo(b),e.safeBlock=next}function l(a,b){for(;b;)/(o|u)l/i.test(b.nodeName)?l(a,b.firstChild):/li/i.test(b.nodeName)&&a.push(b.innerHTML),
b=b.nextSibling}function m(a){function b(a,b){for(;!f[a];)f=f.parentNode;if((f=f[a])&&!/br|h\d|p/i.test(f.nodeName))return h([f],b),!1}var d=c.getRangeAt(0),f,g;if(d.collapsed&&(f=d.startContainer,f.nodeType==3))if(g=f.nodeValue,d.startOffset+a===0&&/^ /.test(g))return b("previousSibling",!1);else if(d.startOffset+a===f.length&&/ $/.test(g))return b("nextSibling",!0)}function q(e,b){if(p(b,46)===!1)return!1;if(!a.browser.webkit)return!0;var d,f=s.block;d=s.list;f=(d||f).nextSibling;var h=c.getRangeAt(0),
g=h.startContainer;if(!h.collapsed||!f||h.startOffset!==g.length)return!0;for(;g.parentNode!==b[0];){if(g.nextSibling)return!0;g=g.parentNode}if(d)g=g.lastChild;if(/(u|o)l/i.test(f.nodeName))f=f.firstChild;f=a(f);d=f.contents();a(g).append(d);f.remove();return!1}function p(e,b,d){var f=c.getRangeAt(0);if(!a.browser.mozilla||d||f.collapsed||ME.util.isNeutralKey(b))return!0;d=f.extractContents();if(e.is(":empty")||/^ *$/.test(e.text()))return d=document.createElement(d.childNodes[0].nodeName),e.html(d),
h([d]),/^8|13|46$/.test(""+b)?!1:!0}var s={},a=jQuery,c=getSelection(),f=document.createRange();return{name:"Preview Mode",items:{"default":{clicked:function(){document.execCommand(this.name,!1,null)}},bold:{tag:"b"},italic:{tag:"i"},alignLeft:{clicked:function(){k("left")}},alignRight:{clicked:function(){k("right")}},alignCenter:{clicked:function(){k("center")}},unorderedList:{clicked:function(a,b,c){r(a,b,c,"ul")}},orderedList:{clicked:function(a,b,c){r(a,b,c,"ol")}},link:{clicked:function(e,b,
d){var f,h,g=c.getRangeAt(0);b={remove:function(){var a=f.text();f.replaceWith(a)},close:function(){e.htmlDiv.focus();e.checkState()}};/ on$/.test(d.className)?(f=a(s.a),d=ME.dialog.link(["Update","Remove","Cancel"]),b.submit=function(a,b){f.attr("href",b).text(a);g.selectNodeContents(f[0]);c.removeAllRanges();c.addRange(g)},h=f.text(),d.val("input.uri",f.attr("href"))):(d=ME.dialog.link(["Create","Cancel"]),b.submit=function(b,e){var d=a('<a href="'+e+'">'+b+"</a>")[0];g.deleteContents();g.insertNode(d);
g.selectNodeContents(d);c.removeAllRanges();c.addRange(g)},h=g.toString());/^\s*$/.test(h)||d.val(".title",h);d.dialog("open",b)}},insertImage:{clicked:function(c,b,d){var f=window.getSelection(),h=f.getRangeAt(0);/ on$/.test(d.className)?(b=ME.dialog.insertImage(["Update","Remove","Cancel"]),s.a&&(d=a(s.a),b.val("input.uri",d.attr("href")),h.selectNode(s.a)),imageNode=a(s.img),b.val("input.imageUri",imageNode.attr("src")),b.val("input.title",imageNode.attr("title"))):b=ME.dialog.insertImage(["Create",
"Cancel"]);b.dialog("open",{submit:function(b,c,d){var e=b=a('<img src="'+b+'"/>');/^\s*$/.test(c)||b.attr({alt:c,title:c});/^\s*$/.test(d)||(e=a('<a href="'+d+'"/>').append(b));h.deleteContents();h.insertNode(e[0]);h.selectNode(b[0]);f.removeAllRanges();f.addRange(h)},remove:function(){imageNode.remove()},close:function(){c.htmlDiv.focus();c.checkState()}})}},formatBlock:{clicked:function(c,b,f){var g,j=[],l;d().replaceWith(function(){l=/(u|o)l/i.test(this.nodeName)?this.nodeName:f.value;g=a("<"+
l+">").addClass(this.className).append(this.childNodes);j.push(g[0]);return g});h(j)}}},getSelection:function(d){var b=c.getRangeAt(0);this.collapsed=b.collapsed;this.leftBorder=new t(jQuery(c.getRangeAt(0).startContainer),d,"previousSibling");this.rightBorder=new t(jQuery(c.getRangeAt(0).endContainer),d,"nextSibling");b.setStartBefore(this.leftBorder.node);b.setEndAfter(this.rightBorder.node);this.rightBorder.borderNode&&a(this.rightBorder.borderNode).nextAll().appendTo("<"+this.rightBorder.block.nodeName+
">").parent().insertAfter(this.rightBorder.block);return b.extractContents()},replaceSelection:function(c,b){this.leftBorder.safeBlock?b.insertAfter(this.leftBorder.safeBlock):c.htmlDiv.prepend(b);this.collapsed?h(b,!0):h(b);/^\s*$/.test(this.leftBorder.block.textContent)&&a(this.leftBorder.block).remove();/^\s*$/.test(this.rightBorder.block.textContent)&&a(this.rightBorder.block).remove()},afterActivation:function(){this.textArea.parent().hide();this.htmlDiv.attr("contentEditable",!0);a.browser.mozilla&&
document.execCommand("styleWithCSS",null,!1)},getSelectionStates:function(){function d(a,b){if(b){var c=b.nodeName,e=a[0].nodeName;c!="#text"&&e!="#text"&&e!=c&&(a=a.find(b.nodeName.toLowerCase()))}return a.parentsUntil(".preview").add(a)}if(!a(document.activeElement).is(".preview"))return{};var b=[],f;f=c.getRangeAt(0).cloneContents().firstChild;b=d(jQuery(c.getRangeAt(0).startContainer),f);f=d(jQuery(c.getRangeAt(0).endContainer),f);/(u|o)l/i.test(b[0].nodeName)&&b[0].nodeName!==f[0].nodeName&&
(b=b.toArray(),b[0]=a("<p>")[0]);return this.buildStateObject(b,s={})},clicked:function(){m(0)},pressed:function(d){this.prototype.pressed.apply(this,[d]);switch(d){case 13:var b;var f=this.htmlDiv;if(p(f,13)===!1)b=!1;else{d=!0;var g,j,l,k=s.block;if(/h[1-5]/i.test(k.nodeName)){j=c.getRangeAt(0);for(g=l=j.endContainer;g.parentNode!==f[0];){if(g.nextSibling){d=!1;break}g=g.parentNode}d&&j.endOffset===l.textContent.length&&(g=a("<p>").insertAfter(k),h(g),b=!1)}}return b;case 8:a:if(b=this.htmlDiv,
d=this.editor,p(b,8)===!1)f=!1;else{g=!0;l=s.block;j=s.list;l=(j||l).previousSibling;var n=c.getRangeAt(0);k=n.startContainer;if(!n.collapsed||!l||n.startOffset!==0)f=!0;else{for(;k.parentNode!==b[0];){if(k.previousSibling){g=!1;if(/li/i.test(k.nodeName))f=!0;else{f=!0;break a}break}k=k.parentNode}if(g){if(j)k=k.firstChild;k=a(k);f=k.contents();a(l).append(f);k.remove();h([f[0]],!0)}else j&&f&&u(d,this);f=!1}}return f;case 46:return q(this,this.htmlDiv,this.editor);case 37:return m(-1);case 39:return m(1);
default:return p(this.htmlDiv,d,this.holdNeutralKey)}},toText:function(){return this.editor.getDataMode().toText()},toHTML:function(){return this.htmlDiv.html()}}});
